### ISSUE TITLE
xwordgrinder t o o  m u c h  s p a c e

### ISSUE THREAD

**Issue by electronoob** [davidgiven/wordgrinder#106]
not sure how to describe this but is there a solution for scaling the x11 version, reducing space between characters etc?

https://i.imgur.com/ydJkobs.png

**Comment by davidgiven** [comment]
I've seen this before, typically when using an unsupported (i.e. non-monospace) font. WordGrinder queries the system for the font size, draws the text expecting it to be that size, but the system can't honour the request and falls back to a much smaller font.

Do you have a `.wordgrinder.lua` file? If so, are you setting `X11_FONT` in it? If not, try creating one and adding this to it:

```
X11_FONT = "Liberation Mono"
```

(or the name of another font you know you have)

**Comment by electronoob** [comment]
sorry for the slow reply but that was great, thank you!
