### ISSUE TITLE
Feature Request: Export ALL documents 

### ISSUE THREAD

**Issue by iandstanley** [davidgiven/wordgrinder#108]
Could you add the ability to export all documents in a set into a single output file

**Comment by semioticrobotic** [comment]
Duplicate, I think, of #78.

**Comment by davidgiven** [comment]
Ha, came here to almost say that...

It's not _quite_ a duplicate: `scripts/exportall.lua` exports every subdocument to a new file. However, I'm currently adding `scripts/concat.lua` which combines all subdocuments into a single one in a (new) WordGrinder file. This should then make it easy to script as something like:

```
wordgrinder --lua scripts/concat.lua "input.wg concat.wg"
wordgrinder --convert concat.wg output.html
```

Then the result could be fed to something like pandoc.
