### ISSUE TITLE
Backspace isn't working

### ISSUE THREAD

**Issue by kostett** [davidgiven/wordgrinder#11]
When I presses backspace, I got the message "UNKNOWN_127 is not bound --- try ESCAPE for a menu". What I'm doing wrong?
Arch Linux, WordGrinder 0.6.0, lxterminal.

**Comment by davidgiven** [comment]
Nothing; your terminal is just generating an unusual key for Backspace. 8 is more usual.

The simplest solution is just to go to the menu, then Navigation -> Delete previous character, and rebind it to your backspace key. Follow the instructions at the bottom of the screen.

What's your TERM set to?

**Comment by kostett** [comment]
Thanks, it works.
TERM="screen", also w/o "xterm" (I'm too lazy to set up uxrvt)

**Comment by davidgiven** [comment]
I've actually added a fix for this so you don't have to remap it, as it's obviously something that's going to effect people.

Thanks for the report!
