### ISSUE TITLE
your 0.7.2 source code release isn't 0.7.2

### ISSUE THREAD

**Issue by crazymonkyyy** [davidgiven/wordgrinder#111]
I can't export to md on arch linux

poking around, 

cli.lua is still
```local export_table =
{
	["wg"] = Cmd.SaveCurrentDocumentAs,
	["odt"] = Cmd.ExportODTFile,
	["html"] = Cmd.ExportHTMLFile,
	["tr"] = Cmd.ExportTroffFile,
	["tex"] = Cmd.ExportLatexFile, 
	["txt"] = Cmd.ExportTextFile,
}```

the aur uses this link https://github.com/davidgiven/wordgrinder/archive/0.7.2.tar.gz

please poke the releases and the aur

**Comment by abenson** [comment]
Markdown output was added 0.7.2.

**Comment by crazymonkyyy** [comment]
Then your release is very very old. The basic arch package grabs the most resent release.

**Comment by davidgiven** [comment]
Markdown export got added via File->Export in 0.7.2, but I forgot to add it to the command line export table. That got fixed recently and will be going out in the upcoming 0.7.3:

https://github.com/davidgiven/wordgrinder/commit/13f2ee0b5c60b5c8f50ef760d7ad75014ac3b5ca#diff-0d6ba04d8ff2b844838a9d29cf9a967e
