### ISSUE TITLE
Spellcheck not recognizing proper nouns or other capitalized words.

### ISSUE THREAD

**Issue by Apreche** [davidgiven/wordgrinder#112]
I'm running Ubuntu 20.04 (inside of Windows Subsystem for Linux, if that matters). I installed wordgrinder 0.7.1-1 from the apt repository. I also installed the `iamerican` ispell dictionary package.

I verified by checking the dictionary file at `/etc/dictionaries-common/words` that it contains many words that are capitalized or are proper nouns. However, when spell checking inside of wordgrinder, it considers any such word to be misspelt.

Here is a screenshot. On the right you can see that AOL is in the dictionary, but wordgrinder considers it to be a misspelt word.

![image](https://user-images.githubusercontent.com/5847/92545612-873bb800-f21e-11ea-9616-197ce08592b3.png)

It also considers `I'm` and `Abelson's` to be misspelt. All other words in that example are considered to be spelled correctly, so some form of spell checking is working properly, just not all of it. I mistakenly thought that words with apostrophes would also be a problem, but it recognizes words like `can't` just fine. It's just the capitalized words that are a problem.

Also, if I add `I'm` to the user dictionary, it is now recognized as being spelled correctly. It's just with the system dictionary that this problem happens.

**Comment by Apreche** [comment]
I figured out why this is happening.

Before checking the spelling of a word, the `IsWordMisspelt` function runs the word through `GetWordSimpleText`. `GetWordSimpleText` returns an all lowercase version of a word. When this lowercase word is compared to `GetUserDictionary` it works because `GetUserDictionary` also processes all words from the user dictionary into lowercase using `GetWordSimpleText`.

This means that if I add `I'm` to my user dictionary that `i'm` will be considered a correctly spelled word by wordgrinder, even though it is not correctly spelled at all. I tested and verified that this is the case. Because of this incorrect case-handling the user dictionary has false negatives and the system dictionary has false positives. 

This isn't easy to fix because any word could be legitimately capitalized if it starts a sentence, but the dictionary file does not contain two versions of every word. You will find `party` in the dictionary, but not `Party`. 

The only true solution I see is to abandon the naive dictionary lookup logic and make an actual call out to a proper spell checking application such as aspell or ispell. They have already solved all the problems related to spell checking, but that obviously adds much more complexity to wordgrinder.

Barring that, I think the following logic would be an improvement, despite still being far from perfect.

1. If only the first letter of a word is uppercase, and it has a case-sensitive match in either dictionary then the word is spelled correctly.
2. If only the first letter of a word is uppercase, and it is the first word in a sentence, and it has a case-insensitive match in either dictionary, then the word is spelled correctly.
3. If any letter in a word other than the first letter is uppercase, and it has a case-sensitive match in either dictionary, then the word is spelled correctly.

I will attempt to make a PR that implements this logic.

**Comment by Apreche** [comment]
I made a PR, but I was unable to detect if a word was the first word in a sentence since the only context given to the spellchecker was a single word. Therefore I had to go for a simpler solution that is less good, but still an improvement from the status quo.

**Comment by davidgiven** [comment]
Sorry for the long delay! I've been looking at this. Wow, spellchecking is ugly.

I've added support for passing information about whether the word is the first of a sentence to the spellchecker, and have taken your code and added support for this, using your rules above as a reference (they seem completely sensible). Your case preservation logic doesn't quite work as it stands as the dictionaries are cached in memory, so `preserve_case` is only honoured on the first call and then ignored afterwards, but I've come up with a reasonable elegant solution. The downside is that it doesn't allow two words to be in the dictionary with different capitalisations --- `Albert` is in the system dictionary, so you can't add `albert` as a valid spelling.

At the moment I can't decide whether this is an acceptable compromise or whether this needs more work. WDYT? The working code is in the `case` branch.

**Comment by Apreche** [comment]
Wow thanks! After I didn't hear back I assumed the project was abandoned. 

I tested your patch locally, and it solves all the problems I had. I wrote a bunch of text, and I didn't notice even one false positive. It also correctly identified all my intentional misspellings. You also solved the problems relating to in-memory caching of the dictionaries, that I was obviously not aware of, and you wrote some tests. It's a big enough improvement over the current release, I say definitely ship it.

Whether it needs more work at this point I think is subjective. For myself and other people writing in languages that have capitalization rules compatible with this logic, I think they will rarely notice anything wrong. However, I'm confident that someone who has spent a lot of time developing a spell checker will be able to point out heaps of edge cases that are going to break this in other ways. Maybe if other users come along with more issues it would be the time to think about fully integrating an external spell checker, and otherwise leave it be.

**Comment by davidgiven** [comment]
No, not abandoned, I've just been working on other things recently... but I need to fix a bug in the Debian distribution, so I'm working through the issue backlog.

Thanks for the sanity check --- I'll merge. And thanks a lot for the PR, you saved me a lot of work.
