### ISSUE TITLE
Wordgrinder for a novice on a Mac?

### ISSUE THREAD

**Issue by aGitjoinsGithub** [davidgiven/wordgrinder#13]
Hi, big fan of David Given's Wordgrinder here, but I don't know much about tarballs, packages, etc. Running OS X 10.9 (Mavericks).  I have managed to get homebrew, but I'm not sure how to go about getting "lua52 ncurses", or perhaps that's two things. 

When I accidentally downloaded the wordgrinder zip file for Windows, the Makefile inside executed when I clicked on it (oops). However, when I downloaded the proper ~ .tar.bz2 file for Unix and clicked that, the Makefile inside just opened as text.

Perhaps  it's just a matter of getting homebrew to find Makefile, but I'm such a novice when it comes to linux-like things that I'm stumbling in the dark here. 

I tried typing 
brew install wget lua52
in a terminal prompt, because I saw some text like that at brew.sh, but the result was
"searching formulae...
searcing taps..."

I think I need a human to point me in the right direction.

**Comment by aGitjoinsGithub** [comment]
Downloaded lua, but have not installed.

**Comment by davidgiven** [comment]
Okay, bad news, I'm afraid. It looks like this no longer works out-of-the-box. It appears that both macports *and* Brew are broken with regards to installing Lua. (Brew have actually *removed* the lua52 package. Macports is refusing to compile anything Lua-related. Sigh.)

It'd certainly be possible to install all the parts manually and then compile WordGrinder, but it's not what I would call 'easy'.

I'm afraid you're probably going to have to wait until Macports and/or Brew and/or Apple get their act together again. Meanwhile I'll see how hard it would be to update WordGrinder to use a version of Lua which Brew and Macports actually support, but it's not going to happen soon.

Sorry.

**Comment by aGitjoinsGithub** [comment]
That's ok, I appreciate the prompt reply, and I'll continue to use the
Linux version when I can.
Dave

**Comment by davidgiven** [comment]
You know what? I was wrong --- it *does* work with brew.

The commands are:

    brew install --build-from-source lua
    luarocks install luafilesystem

Then you can build WordGrinder in the usual way:

    tar xvzf wordgrinder-0.6.tar.gz
    cd wordgrinder-0.6
    make
    make install

That'll leave you with ~/bin/wordgrinder, which you should be able to run from a terminal.

**Comment by aGitjoinsGithub** [comment]
Excellent. Thank you, sir!
