### ISSUE TITLE
Option to function as text editor (for use with Mutt)

### ISSUE THREAD

**Issue by jvarsoke** [davidgiven/wordgrinder#14]
I would really like to use Wordgrinder in place of Nano for my email editor of choice in Mutt on Linux servers.

[it's rather silly to use a stripped down text editor for email, when Wordgrinder can offer much more in the way of writing prose)

To do so, I think it would need some commandline options to read a text file, parse the \n correctly (or swallow them, I guess), support the typical reply formating ">", and save as a text-file (or maybe push the resulting text to STDOUT (not sure how Mutt/Pine interface with the editor).  It would also need to support hard-CR vs. soft-CR.

Since Wordgrinder is rather light-weight, I'd like to be able to use it for any command-line scenario when I want to quickly edit a file that really more in common with a short word-processing session, than a code-editor.  However, in these cases the desire is for the resulting file just to be text without any special formating.

**Comment by davidgiven** [comment]
Reading in unformatted text from an email and then formatting it is pretty hard --- there's all kind of fuzzy heuristic choices that's hard to test. However, if you could find a third-party product which could convert unformatted text into, say, HTML, then it'd be trivial to convert that to .wg format for editing:

    wordgrinder --convert file.txt file.wg
    wordgrinder file.wg
    wordgrinder --convert file.wg file.txt

Although I do agree; WordGrinder would work rather nicely as an email editor...

**Comment by jvarsoke** [comment]
I'm not sure exactly what you're referring to by requiring fuzzy heuristics.  To be clear, I'm only talking about a level of support currently provided by Nano (Pico).  The only change would be managing hard/soft CRs and reply marks ">" with wordwrap.

I'm not talking about any thing fancy like interpreting non-text emails.

I doubt Nano has code in it to parse Email in any way not already provided to it by Mutt.  But I haven't looked at the source, so I could certainly be wrong.

**Comment by davidgiven** [comment]
It's not that easy. For example... what's a paragraph? Blocks of text separated by whitespace? What about lines beginning with whitespace? Do they start paragraphs? What about indented blocks --- how do we distinguish those from multiple paragraphs? What about lines that just happen to start with a > but aren't quotations? What about multiple levels of quotations? What about email which isn't line-wrapped and uses one line per paragraph --- how do we tell that from a single paragraph of line-wrapped text?

I'm not saying that these problems haven't been solved (although looking at the way Thunderbird mangles quotation detection it's quite plausible that they *haven't* been solved), but I don't want to go there right now.

(But if you can find a third-party library that does a reasonable job of getting it right, it would be a nice thing to have.)

**Comment by jvarsoke** [comment]
It's probably my lack of understanding of how WG is structured internally; perhaps you're over-complicating it for a reason.

I don't think there's a non-WG specific reason you'd need to know what a paragraph is.  Nano doesn't have any clue.  Neither does VIm.  Both suffice as mail editors.  Nano gives the option for the user to manually massage things with it's "CTRL-J" function.  But it's pretty limited.  And also sufficient.

Of course, then the question might be why WG at all?  Why not use Nano?  Fair point.  I was thinking that advances in Spellchecking (maybe in-line) would be nice.  The word-wrap is better too.  I'm sure you can think of other advantages WG would have in this setting.

But I get the sense you're not very interested in this usecase since you closed the topic already.

**Comment by davidgiven** [comment]
Yeah, sorry. I don't feel that that's part of WordGrinder's core competency and is best handled by external tools. There are some things needed for email editing that WordGrinder plain doesn't do, like nested quotations (try it in nano; it understands them and formats them properly).

My preferred option here is to use external tools to convert the email to something like HTML, and then edit that with WordGrinder, and then convert back again.
