### ISSUE TITLE
Desktop file?

### ISSUE THREAD

**Issue by funnelfiasco** [davidgiven/wordgrinder#141]
Over the weekend or sometime in the very near future, I'd planned on adding a `.desktop` file for the Fedora xwordgrinder package so that it appears in desktop environment menus. Is that something you'd like me to submit upstream and if so, where's a good place to put it? I was thinking `extras/` alongside the icon file, but if you have somewhere else in mind I'm happy to put it somewhere else.

**Comment by davidgiven** [comment]
That's a good idea --- yes, one would be great. I'd use it for Debian too.  `extras` would be ideal. Thanks very much!
