### ISSUE TITLE
Markdown Problem with Headings

### ISSUE THREAD

**Issue by williamriverdale** [davidgiven/wordgrinder#143]
Excuse me, I am having a problem where when I export to markdown (am using linux), wordgrinder places a backslash in front of the hash. Example:

Instead of looking like this:

# Chapter One

It looks like this:

\# Chapter One

How do I fix this issue?

**Comment by davidgiven** [comment]
Thanks for the report --- but I can't duplicate this. Which version are you using? (File -> About)

Also, version 0.8 is coming out any day now, and all this code has been largely replaced, so it might be worth trying that.

**Comment by williamriverdale** [comment]
Thank you for your reply. I am using version 0.7.2 (file format version 7)

 I will wait for the 0.8. :)
