### ISSUE TITLE
Can't [TAB] (instead get italics)

### ISSUE THREAD

**Issue by jvarsoke** [davidgiven/wordgrinder#15]
Unix (Debian testing)
Gnome Terminal

Pressing "TAB" italicizes instead of tabbing.

**Comment by davidgiven** [comment]
Sorry, can't do anything about this --- TAB and ^I produce the same keycode in curses. (The X11 and Windows versions don't suffer from this problem).

It's documented in the README.wg.

**Comment by jvarsoke** [comment]
To promote user uptake, you might want to detect the situation the very first use of WG and prompt the user with both the problem they'll experience and a work around (how to remap the Italics command).  Just telling them to use X11 is probably not great, since the whole attraction to WG is the in-terminal non-gui interface.

Is there an easy way to remap the command? (my lua is weak)

**Comment by davidgiven** [comment]
You don't even have to use Lua --- just go into the style menu and change ^I to point to something else.

**Comment by jvarsoke** [comment]
Ah, didn't see the commands to unbind at the bottom of the screen.  Got it now.  Thanks.

How do I persist those changes?  The reset after I drop out of WP.  (Throwing me a link to on-line documentation indicating this process would be a totally fair response)

**Comment by davidgiven** [comment]
They get saved automatically as part of your document, along with nearly all your other document settings.

**Comment by jvarsoke** [comment]
Okay, but do you think it's more normal to change a keybinding per-document, or for it to change how you interact with a program?

I could see the corner case, where you'd want to do something very specific in a particular document in a certain way.  But usually, if I change the bindings of a program, I expect all uses of that program to abide by my choice.  Maybe offer a way to set this in the ~/.wordgrinder.lua ?

**Comment by davidgiven** [comment]
For me? Per document. That's why I implemented it like that!

You can set this in .wordgrinder.lua. It's documented (rather poorly) in README.wg. See section 1.9, 'Manually configuring WordGrinder'. It's all a bit clunky but works.

(Rather than specifying a command id as the parameter, you can supply any arbitrary Lua function. e.g. I have this:

    OverrideKey("F4", function()
        Cmd.ExportHTMLFile("/tmp/output.html")
        os.execute("xclip -selection clipboard /tmp/output.html")
    end)

Pressing F4 copies the current subdocument to the X clipboard as HTML.)
