### ISSUE TITLE
Permanently disable the status bar

### ISSUE THREAD

**Issue by RiccardoPP** [davidgiven/wordgrinder#151]
Hello,
I'd like to permanently disable the status bar in xwordgrinder. It's possible? I've tried to put:

`.statusbar: false`

in `settings.dat` but with no success. I need to recompile the software?

Thank you.

**Comment by davidgiven** [comment]
Hello --- sorry, haven't got round to replying to your email yet...

If you're using 0.8, then the easiest way is to set up a document the way you like it, save it as a template, and then whenever you create a new document from that template all the settings will apply. If you're not, you will need to modify the program. You can change the default value at https://github.com/davidgiven/wordgrinder/blob/master/src/lua/document.lua#L704.

**Comment by RiccardoPP** [comment]
Hi David, I'll try to recompile. Thanks for the quick reply!
