### ISSUE TITLE
Spellchecker returns misspelled words after characters "!" and "?"

### ISSUE THREAD

**Issue by alecstein** [davidgiven/wordgrinder#155]
I'm using aspell downloaded from homebrew, running wordgrinder 0.8.

Spell checking works fine except for any time a sentence ends with an "!" or a "?" such as

![spellchecker](https://user-images.githubusercontent.com/16236421/103302873-7f647700-49b9-11eb-86c0-76b6cc387ffe.png)

You can see that there are some exceptions, i.e. if the punctuation is followed by a two-letter word, no errors are thrown.

**Comment by alecstein** [comment]
Adding: if the word after the punctuation is not capitalized, spell check does not throw an error.

**Comment by davidgiven** [comment]
Urgh. This is because the spellchecker treats words at the beginning of a sentence specially, and it detects these based on whether the previous word ends in a full stop... which in hindsight was kinda stupid. Will fix.
