### ISSUE TITLE
Segfault using exportall.lua on an older .wg file

### ISSUE THREAD

**Issue by larrykollar** [davidgiven/wordgrinder#156]
With the latest source, attempting to do exportall on a .wg file from 0.7.2 gave a segfault on MacOS X Catalina:

```
% ~/Projects/wordgrinder/bin/wordgrinder-builtin-curses-release--lua ~/Projects/wordgrinder/scripts/exportall.lua mybook.wg output.md
zsh: segmentation fault  ~/Projects/wordgrinder/bin/wordgrinder-builtin-curses-release—lua
%
```

It worked after opening the book and saving it, thus updating the book to the latest version. So you might need to add a test for older books, and include a message to update the book before running scripts on it.

**Comment by davidgiven** [comment]
Yup, I can duplicate this --- thanks! Crashes like that shouldn't really be possible...
