### ISSUE TITLE
Markdown export produces HTML instead

### ISSUE THREAD

**Issue by semioticrobotic** [davidgiven/wordgrinder#162]
When I ask wordgrinder 0.8 to export a document in Markdown format, the file I receive contains HTML tags instead of Markdown syntax.

For example, when I export **text like this**, I receive a file that contains

`<b>text </b><b>like </b><b>this</b>`

when what I expect to receive is 

`**text like this**`

**Comment by tuffnatty** [comment]
@semioticrobotic Basically, it should still work as HTML is a subset of Markdown. However, not sure if that was the idea.

**Comment by semioticrobotic** [comment]
I'm sure it still works for the machine, @tuffnatty, but as Markdown's advantage is its intuitive, human-readability, I'd prefer the expected/intended output over the tag-filled one.

**Comment by davidgiven** [comment]
Sorry, been working on other projects --- but yes, the HTML export is deliberate. It's because of problems with the Markdown syntax being ambiguous when it comes to nested styles. That said, `</b><b>` is inelegant and should be fixed.

**Comment by semioticrobotic** [comment]
Interesting, @davidgiven. Thanks for responding. I'm not sure what you mean by "nested styles" in this case, but I'm sure you have a better understanding of Markdowns limitations than I do.

**Comment by davidgiven** [comment]
Sorry for the delay, been busy with other things... TBH, I forget the exact details because it was a while ago, but I tried to make it work and failed. Also, Markdown doesn't support underlining, so I would need to mix in HTML tags and Markdown markup anyway.

I'm going to close this as infeasible, but I'm open to suggestions...
