### ISSUE TITLE
Bug: copy and paste from other apps does not work

### ISSUE THREAD

**Issue by hrumhurum** [davidgiven/wordgrinder#164]
## Environment

- Windows 10 Version 1909
- x64

## Steps to reproduce

1. Launch a web browser (I did with Chrome)
2. Launch a WordGrinder
3. Go to some website (any)
4. Select some text and copy it to the system clipboard
5. Paste the text to WordGrinder (Ctrl+V or by menu, the outcome is the same)

## Expected results
- The text gets pasted and then appears as a part of WordGrinder document

## Actual results
- Nothing happens

## Notes
- Copy and paste works fine inside WordGrinder but not between the apps in a system

**Comment by davidgiven** [comment]
That's actually correct --- integrating with the system clipboard turns out to be really hard.
