### ISSUE TITLE
Prime save filename from the commandline

### ISSUE THREAD

**Issue by jvarsoke** [davidgiven/wordgrinder#17]
Typical expectations for an editor is to issue the desired filename for a new file from the command line:

$ wordgrinder foo.wg

WG complains about the file not being there (kinda unnecessary).  But then when you hit CTRL-S it should create a "foo.wg" w/o prompting for a filename . . . since you already told it what you wanted to edit from the command line.

**Comment by davidgiven** [comment]
Yes, that's a good idea. I'll see what I can do.

**Comment by davidgiven** [comment]
This should be done.
