### ISSUE TITLE
[SDL] GUI version error

### ISSUE THREAD

**Issue by funnelfiasco** [davidgiven/wordgrinder#170]
I'm building the in-development version on Fedora Linux 34. It builds successfully, but when I launch it, I get

~~~~
Lua error: [string "src/lua/_prologue.lua"]:38: read from undefined local 'FONT_REGULAR'
stack traceback:
        [C]: in function 'error'
        [string "src/lua/_prologue.lua"]:38: in function <[string "src/lua/_prologue.lua"]:36>
        [C]: in function 'initscreen'
        [string "src/lua/main.lua"]:148: in function 'WordProcessor'
        [string "src/lua/main.lua"]:390: in function <[string "src/lua/main.lua"]:255>
~~~~

The SDL2_ttf package is installed. I'm not sure where to go with debugging this.

**Comment by davidgiven** [comment]
...okay, I know what that is; I bet you tried the -debug version, right? Try the -release version instead (which doesn't have that check) and it should be fine. Thanks!

**Comment by funnelfiasco** [comment]
Yep, that was it!
