### ISSUE TITLE
[SDL] Missing icons?

### ISSUE THREAD

**Issue by funnelfiasco** [davidgiven/wordgrinder#171]
Switching to the "release" binary (#170) got the GUI to launch. But it looks like maybe there's missing icons or glyphs in the menu? Not sure what is expected here.

![image](https://user-images.githubusercontent.com/445852/123662235-417acb00-d803-11eb-8970-50b182f19262.png)

**Comment by davidgiven** [comment]
Yup, good point --- needs fixing.

**Comment by funnelfiasco** [comment]
Thanks. Just wanted to make sure it wasn't an error on my part before I share my Fedora Copr builds.

**Comment by Begasus** [comment]
Can confirm the issue being present in a "just cloned" repo on Haiku
