### ISSUE TITLE
Line Endings by OS

### ISSUE THREAD

**Issue by nathansmith11170** [davidgiven/wordgrinder#174]
By default, the wordgrinder files (.wg file type) do not have the same line-endings on Windows and Linux, which means that if the file is saved by wordgrinder on a linux machine that same file cannot be opened my wordgrinder on Windows.
I work with wordgrinder and keep a private repository using git. I resolved the issue for my purposes by standardizing the line endings with a gitattributes file, but it might be worth having the application always use a standard line ending instead of following the OS to avoid this compatibility issue.

**Comment by davidgiven** [comment]
Can you double check your git configuration, please? That absolutely shouldn't happen, and I've just checked that I am opening the files in binary mode; so for the line endings to change suggests a bug in Lua (or at least the version I'm using). Do you have any problems opening the Readme.wg file?

**Comment by nathansmith11170** [comment]
Sorry it took me a bit to reply. I got it working weeks ago by putting
`* text=auto eol=lf
*.{cmd,[cC][mM][dD]} text eol=crlf
*.{bat,[bB][aA][tT]} text eol=crlf`
into .gitattributes

But I'm not sure if that's what you're asking. The default git repository did not let me open the same .wg file on Lubuntu and Windows 10. If I saved it on Lubuntu then it wouldn't open on Windows, but if I saved it on Windows then it would open on Lubuntu.
It does sound more like Git being a git.

**Comment by davidgiven** [comment]
Sorry for the delay --- been focused on other projects... yes, this sounds like git is screwing up the line endings during checkout. It shouldn't be doing this silently changing files on checkout is a terrible idea. Try copying the file physically between Windows and Linux and seeing if it can be opened both ways.

If you look at the README.wg on Windows, it should have lf-only line endings, which is what WordGrinder expects. However, I'll look into adding support for reading files with crlf line endings for added robustness.

**Comment by davidgiven** [comment]
Yep, was easy.
