### ISSUE TITLE
global settings getting reset after running --convert on command line

### ISSUE THREAD

**Issue by nyex** [davidgiven/wordgrinder#177]
Hello

I have zero knowledge of lua but wordgrinder is my go-to text editor for novel writing. Recently I've started using a script to convert/export my main document to a .md file and noticed a weird behavior.

I usually write with the following 'global' settings:

```
.globalSettings.lookandfeel.denseparagraphs: true
.globalSettings.lookandfeel.enabled: true
.globalSettings.lookandfeel.fullstopspaces: false
.globalSettings.lookandfeel.maxwidth: 80
.globalSettings.lookandfeel.terminators: false
```

This is how they appear in the settings.dat file. Every time i run the script that uses the command-line convert option `wordgrinder --convert draft1.wg:"draft_set" draft_set.md` and re-open my draft1.wg file, dense paragraphs and widescreen are disabled again. I see it happens because settings.dat gets overwritten to default settings: 

```
.globalSettings.lookandfeel.denseparagraphs: false
.globalSettings.lookandfeel.enabled: false
.globalSettings.lookandfeel.maxwidth: 80
.globalSettings.lookandfeel.terminators: true
```

... which is a bit annoying, because I don't know how and where to set my preferences to default. I tried creating a .wordgrinder.settings file but apparently it conflicts with the settings.dat one that gets generated automatically. I apologize if this is explained somewhere, but I've been looking into this for a few weeks now and have not found a solution.

**Comment by davidgiven** [comment]
Hmm. That does sound like a bug. I'll look into it. Thanks for the report.

**Comment by davidgiven** [comment]
I've got a fix for this; it should hit git master shortly. Thanks for the bug report!
