### ISSUE TITLE
Add mouse support

### ISSUE THREAD

**Issue by lproven** [davidgiven/wordgrinder#195]
It would be useful to be able to control the menus, and select text, using the mouse.

Both in X and on the console.

For comparison, the Tilde editor does this on the console via the `gpm` mouse driver.

**Comment by davidgiven** [comment]
I agree this is desireable, but it's both complicated (so many edge cases...) and is incompatible with the current fixed cursor line behaviour (see #89). So, I'd need to change that first. I actually think that's a good idea anyway.

**Comment by davidgiven** [comment]
Edit control can be done with the mouse, but you're right in that menu control would be a good idea too.

**Comment by davidgiven** [comment]
Turns out that menus are already mouse controllable!

**Comment by davidgiven** [comment]
...and so are the forms! The things you discover when you go and look...

Closing, as this seems to be done.
