### ISSUE TITLE
Disable vertical text centring

### ISSUE THREAD

**Issue by lproven** [davidgiven/wordgrinder#197]
I find the way the app tries to keep the cursor in the middle of the screen distracting. I prefer the more conventional behaviour of scrolling only when the cursor is going to go off-screen. 

I suggest the ScrollLock key for this, but many distros disable it. I don't know if the app could trap it just when it has focus.

If not, a preference in Global Settings would do.

**Comment by lproven** [comment]
Overlaps with https://github.com/davidgiven/wordgrinder/issues/89

**Comment by davidgiven** [comment]
Duplicate of #89
