### ISSUE TITLE
Can handling "document sets" be an option?

### ISSUE THREAD

**Issue by lproven** [davidgiven/wordgrinder#199]
I find this overcomplicated and confusing. 

Can I just have a tick-box to turn that feature off, so it works on one file at a time? If I need two files, I will open two instances, on different vconsoles if necessary.

Ideally IMHO this would be off by default.

**Comment by davidgiven** [comment]
Turning them off completely is actually pretty hard as they're used internally for things like the user spellchecker dictionary and the scrapbook. What's specifically the problem? You should just be able to ignore them if you're not using them.

**Comment by davidgiven** [comment]
Closing for cleanup.
