### ISSUE TITLE
lua-filesystem

### ISSUE THREAD

**Issue by Munchotaur** [davidgiven/wordgrinder#2]
After uninstalling wordgrinder through apt-get, I was recommended to autoremove lua-filesystem. The git version needs this installed so perhaps it should be added to the prerequisite packages on README.md?

**Comment by davidgiven** [comment]
That requirement is going away; 0.6 will use the built-in version instead of the system one. (Because it makes the different platforms more consistent and therefore easier to test, and also because older versions of Ubuntu don't have it anyway.)
