### ISSUE TITLE
Localised error messages don't work

### ISSUE THREAD

**Issue by davidgiven** [davidgiven/wordgrinder#20]
We look for the error "No such file or directory" to detect a missing .wordgrinder.lua file. This doesn't work on a system with a non-English locale. e.g. on a Portugese system, the error is: "Arquivo ou diretório não encontrado".

**Comment by emk2203** [comment]
Could it be an option to just `touch wordgrinder.lua` during initialization?

**Comment by davidgiven** [comment]
Fixed --- turns out there's a semi-documented third parameter to io.open which contains the errno.
