### ISSUE TITLE
Disable GUI / colors in terminal, or allow to customize

### ISSUE THREAD

**Issue by aarondodd** [davidgiven/wordgrinder#212]
If I'm an idiot please forgive me.

Since upgrading to 0.9 the terminal version of wordgrinder now overrides my terminal colors with its built in theme. I see a GUI menu option and can change color themes to one of three choices, but I'd like to either disable this feature or be able to specify the colors.

Under both 0.8 and 0.9 I run with `TERM=xterm-256color`.

As a workaround I can change my `TERM=xterm` (-no 256color) but a settings.dat entry would be nice. 

I tried changing:

`.globalSettings.lookandfeel.enabled: true`

to `false` but it didn't make a difference.

**Comment by davidgiven** [comment]
Oops --- I forgot that needed to be an option! Will fix.

**Comment by davidgiven** [comment]
Fixed, finally!
