### ISSUE TITLE
Customize the font (console)

### ISSUE THREAD

**Issue by RiccardoPP** [davidgiven/wordgrinder#219]
Hello, thanks for Wordgrinder!

I'm using it on a framebuffer Linux console and I'd like to set a different font (bolder and bigger than my standard terminal font). I've no X11 server, just a framebuffer.

I could create an alias to change the font on WG launch. For example:

`alias wg="setfont /usr/share/consolefonts/ter-128b.psf.gz && wordgrinder"`

But I need to set back the original font on exit and I don't known where to add a command (for ex: `setfont /usr/share/consolefonts/ter-118b.psf.gz`) in the source code before (or just after) the quit one.

May you help me? Thanks.

**Comment by NikkSaan** [comment]
Hello, @RiccardoPP! You don't need to edit the source code. This should work.
```
alias wg="setfont /usr/share/consolefonts/ter-128b.psf.gz; wordgrinder; setfont /usr/share/consolefonts/ter-118b.psf.gz"
```
