### ISSUE TITLE
Installed 0.8 successfully on Archbang once, but now it's failing to install

### ISSUE THREAD

**Issue by jim9835** [davidgiven/wordgrinder#220]
Have successfully installed 0.8 on Manjaro and once on Archbang (using the git clone > makepkg method from the Arch AUR), but now can't replicate the Archbang success.

I'm only a copy-and-paste code person, so get a bit stuck when things go awry.

Could you let me know what's going on here and how I can fix it?

`==> Validating source files with sha256sums...
       0.8.tar.gz ... Passed
==> Extracting sources...
  -> Extracting 0.8.tar.gz with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
/bin/sh: line 1: LC_ALL: command not found
Bootstrapping build
/bin/sh: line 1: cc: command not found
make: *** [Makefile:195: .obj/lua] Error 127
==> ERROR: A failure occurred in build().
    Aborting...`

**Comment by jim9835** [comment]
OK. Couldn't help but spend some more time on this myself when I should be working...

I fix this by installing gcc and pkg-config.

**Comment by davidgiven** [comment]
Glad to hear it!
