### ISSUE TITLE
Makefile needs small modification to compile on Fedora.

### ISSUE THREAD

**Issue by SurfaceThought** [davidgiven/wordgrinder#23]
Hello,

In fedora lua is called by "lua" not "lua5.2", so in order for it to compile it is necessary to change the include statement for lua in the makefile. While I really have no idea, I imagine that this is probably the case for RHEL and CentOS as well. Perhaps it is worth adding a note to the readme?

**Comment by funnelfiasco** [comment]
This was fixed in PR #38. Also, wordgrinder is now available in the Fedora repos if you don't want to build it yourself.
