### ISSUE TITLE
Justify text & mapping keys

### ISSUE THREAD

**Issue by ajrossnz** [davidgiven/wordgrinder#230]
Hi, I would really like the ability to justify text (as in fill the available page rather than left justify which is the global default). This is a fairly standard option in all word processors. Whilst I appreciate wordgrinder is often suggested for use with other 'prettyfiers', I commonly don't have an option to run a GUI when I am on the move, so doing so is not an option on occasion, thus the reason I use Wordgrinder.

Secondly, it would be awesome if there was some way to map keys such as CTRL-; or CTRL-P for example to remap END, PGDN etc as my terminal cannot support PGDN/UP and END etc. When I enter these sequences into WG it just says that these are already bound or in some cases, provides no error at all.

**Comment by davidgiven** [comment]
Closing for cleanup.
