### ISSUE TITLE
No rule to make target 'src/c/emu/lua-5.1.5/*

### ISSUE THREAD

**Issue by ubuntupunk** [davidgiven/wordgrinder#233]
I have all the recommended deps installed on ubuntu 22.04. 

`make: *** No rule to make target 'src/c/emu/lua-5.1.5/*.[ch]', needed by '.obj/lua'.  Stop.`

**Comment by davidgiven** [comment]
This should work (and the github CI scripts prove it!). Which version did you download?

**Comment by ubuntupunk** [comment]
[wordgrinder-0.8-minimal-dependencies-for-debian.tar.xz](https://github.com/davidgiven/wordgrinder/releases/download/0.8/wordgrinder-0.8-minimal-dependencies-for-debian.tar.xz)

**Comment by ubuntupunk** [comment]
liblua5.3-dev is already the newest version (5.3.6-1build1).

**Comment by davidgiven** [comment]
Don't use that one. Use the proper source release. That package (as the text above says!) is for special purposes only.

I'd actually recommend you get the latest development release rather than 0.8, as 0.8 is pretty old.

**Comment by davidgiven** [comment]
Closing for cleanup.
