### ISSUE TITLE
build error: malformed number

### ISSUE THREAD

**Issue by kbarni** [davidgiven/wordgrinder#239]
I get a *"Malformed number"* error while building the LUA files:

    Lua error: [string "src/lua/_prologue.lua"]:67: Malformed number

This happens for every floating point number declaration.

It seems that it expects comma as decimal separator (as I can solve it by replacing `0.8` by `0,8`).

As a workaround, I set LC_NUMERIC to en_US from fr_FR

I wonder if it's possible to set it by default ? Probably put a `os.setlocale("C")` somewhere?

**Comment by davidgiven** [comment]
Changing LC_NUMERIC to fr_FR doesn't duplicate that for me, but I believe you... that sounds like a Luau bug.

Could you do an update (I've just make a change), then do:

```
make clean; make NINJAFLAGS="-j1 -v"
```

...and attach the build log, please?

**Comment by davidgiven** [comment]
I can duplicate it --- thanks!
