### ISSUE TITLE
Still doesn't compile on Mac Yosemite

### ISSUE THREAD

**Issue by frankjonen** [davidgiven/wordgrinder#24]
Error log attached. Steps taken as outlined in [Issue 13](https://github.com/davidgiven/wordgrinder/issues/13)
I see lua.h in `ls $(brew --prefix)/include`

There seems to be something at odds with the config and the way globals are set perhaps?
Any ideas how to get it to work?

[error.txt](https://github.com/davidgiven/wordgrinder/files/555065/error.txt)

**Comment by frankjonen** [comment]
I've reinstalled lua now seven times since that's what everybody is saying. No differing result. Not wasting any more time with it. Just tried again for the 8th and last time. Maybe someone will do a brew package at some point. :/

**Comment by davidgiven** [comment]
I know this is old, but... I've just rebuilt the entire build system (as well as making lots of bugfixes), and it builds out-of-the-box on OSX now, at least on OSX 10.10:

https://travis-ci.org/davidgiven/wordgrinder/jobs/259531816

Would you like to give it another try and let me know how it works? Instructions should be in the README.

**Comment by frankjonen** [comment]
Just gave it a try. No luck.

without sudo but from the admin account:

> wordgrinder-master sysop$ make
> Bootstrapping build
> Windows toolchain: not found
> sh: pkg-config: command not found
> Curses package 'ncursesw': not found
> sh: pkg-config: command not found
> FreeType2: not found
> sh: pkg-config: command not found
> Lua package 'lua-5.1': not found
> sh: pkg-config: command not found
> Lua package 'lua-5.2': not found
> sh: pkg-config: command not found
> Lua package 'lua-5.3': not found
> sh: pkg-config: command not found
> Lua package 'luajit': not found
> ninja: error: opening build log: Permission denied

with sudo from the same account: 
 
> ninja: error: unknown target 'all', did you mean 'dev'?
> make: *** [all] Error 1

```

**Comment by davidgiven** [comment]
Yosemite is 10.10, and the version on Travis is 10.11, so they should be pretty similar.

If it's not finding pkg-config, then that sounds like Homebrew's not installed. But it found ninja, so there must be something there... you haven't changed your PATH, have you?

Could you try (as a normal user):

    $ brew install pkg-config
    $ make clean
    $ make

...and let me know what happens, please?

(Sorry, I don't actually have shell access to an OSX machine --- I did the Travis setup blind.)

**Comment by frankjonen** [comment]
It looks like the version on this Travis thing is the same as on here. I couldn't figure out what to do with the Travis link so I pulled it from here.

Can't do as a normal user. It's set up so only admins have write permissions to the brew directories.

After installing pkg-config here's what I got.

> Bootstrapping build
> Windows toolchain: not found
> Curses package 'ncursesw': not found
> FreeType2: found
> Lua package 'lua-5.1': not found
> Lua package 'lua-5.2': found
> Lua package 'lua-5.3': not found
> Lua package 'luajit': not found
> The preferred Lua package is: 'internallua'
> ninja: error: opening build log: Permission denied
> make: *** [all] Error 1

Lua is installed via brew, so is ncurses. 

Maybe this helps:

### ncurses
> ncurses: stable 6.0 (bottled) [keg-only]
> Text-based UI library
> https://www.gnu.org/software/ncurses/
> /usr/local/Cellar/ncurses/6.0_2 (3,827 files, 10.4MB)
>   Poured from bottle on 2016-10-27 at 01:32:10
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ncurses.rb
> ==> Dependencies
> Build: pkg-config ✔
> ==> Caveats
> This formula is keg-only, which means it was not symlinked into /usr/local,
> because macOS already provides this software and installing another version in
> parallel can cause all kinds of trouble.

### Lua

> lua: stable 5.2.4 (bottled)
> Powerful, lightweight programming language
> https://www.lua.org/
> /usr/local/Cellar/lua/5.2.4_4 (143 files, 697.4KB) *
>   Poured from bottle on 2016-12-14 at 19:13:28
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/lua.rb
> ==> Options
> --with-completion
> 	Enables advanced readline support
> --without-luarocks
> 	Don't build with Luarocks support embedded
> --without-sigaction
> 	Revert to ANSI signal instead of improved POSIX sigaction
> ==> Caveats
> Please be aware due to the way Luarocks is designed any binaries installed
> via Luarocks-5.2 AND 5.1 will overwrite each other in /usr/local/bin.
>

**Comment by davidgiven** [comment]
We're making progress!

There's two things here: firstly, the build system is failing to realise you're on OSX and is using the wrong ncurses package; I've fixed that (I hope). Secondly, there's a file with the wrong permissions and ninja won't start until it's removed. I'll note that in the README.

(Also, you don't need the lua and ncurses Homebrew packages any more.)

As the admin user, but not with sudo, try:

    $ git pull
    $ rm -f .ninja_log
    $ make

If that works, you should be able to install with:

   $ make install PREFIX=whatever

**Comment by frankjonen** [comment]
![screen shot 2017-08-01 at 17 19 03](https://user-images.githubusercontent.com/3016983/28832729-987cee82-76dd-11e7-8d29-5a368ee25f04.png)

**YESSS!!!**

Two things:

1. Typing in `wordgrinder` does nothing. It needs to be set as an executable first. (maybe add that to the script)
2. The `sudo make install PREFIX=/usr` installs it to the respective user's home folder for some reason. I'll just move it to the regular binaries.

**Comment by frankjonen** [comment]
Also thank you for your patience and support!

**Comment by davidgiven** [comment]
That's excellent news!

Both running `wordgrinder` and `make install PREFIX=` work on my system here, so I don't know what's going on here. Homebrew oddities, maybe? I'd need an OSX system to play with to find out for sure. But I think I'll call this working, now. OSX has always been painful to build on, and it's good to know it works.

Thank you very much for the assistance!
