### ISSUE TITLE
Internal error when changing global settings

### ISSUE THREAD

**Issue by kbarni** [davidgiven/wordgrinder#240]
I get the following error in a dialog when changing in *Global settings* widescreen mode, terminators above/below document, dense mode etc.

    [string src/lua/forms.lua"]:836: attempt to call missing method 'key' of table [string src/lua/forms.lua"]:836 function Run [string src/lua/look-and-feel.lua"]:190 function ConfigureLookAndFeel [string src/lua/menu.lua"]:121 [string src/lua/menu.lua"]:565 function runmenu  [string src/lua/menu.lua"]:584 function runmenu [string src/lua/menu.lua"]:584 function runmenu [string src/lua/menu.lua"]:326 function activate [string src/lua/menu.lua"]:121 [string src/lua/main.lua"]:193 function handle_key_event [string src/lua/main.lua"]:263 function eventloop [string src/lua/main.lua"]:278 function WordProcessor [string src/lua/main.lua"]:436 function main

**Comment by davidgiven** [comment]
Oops --- fixed. Thank you for the bug report!
