### ISSUE TITLE
Thanks for wonderful software, and display glitch in Windows

### ISSUE THREAD

**Issue by securetly** [davidgiven/wordgrinder#245]
First, let me say a HUGE thank you for Wordgrinder. It is pretty much exactly what I have been looking for. I am running on a Windows 11 PC and, when using the console version, it is perfect. However, when I run the GUI version, some of the text is unreadable. I *think* that it is trying to show italics but I am not sure. Here is a screenshot of the readme document as it displays on my screen.

<img width="710" alt="wordgrinder" src="https://github.com/davidgiven/wordgrinder/assets/63720581/cf241a9b-a23b-4a8e-8664-eb82266ed45d">

I have tried this on two PCs -- a Lenovo T14s and an Intel NUC, with exactly the same issue, so I don't think that this is related to a particular PC.  Is there something I am doing wrong? Do I need to install any particular font (or how do I specify the font to use)?

Again, I will probably mainly use the console version -- that is actually my primary interest -- but wanted to bring this to your attention.

Regards

Jim Karabatsos

**Comment by davidgiven** [comment]
Thank you for the kind words!

What you're seeing is an artifact of Windows font rendering; the default font doesn't have an italic form and if you ask Windows to try to draw it, it fakes it --- badly. Your options are to either change the font via the top-left menu (click on the icon), or else use the 0.9 development version which has a completely rewritten GUI which doesn't suffer from that problem.

**Comment by davidgiven** [comment]
Closing for cleanup.
