### ISSUE TITLE
Ctrl-P is bound yet not recognized

### ISSUE THREAD

**Issue by moonmaster9000** [davidgiven/wordgrinder#249]
Upon pulling down and compiling and installing master (with my backtick spellchecking fix that you accepted), I now discover that "Ctrl-P" isn't recognized, yet the menu does claim that it is bound. Since I use Ctrl-P constantly to set the text style, I'm keen to see this fixed. In the meantime, I'm using the slighly longer keystroke sequence "Esc->S->P" to navigate to that same menu.

**Comment by davidgiven** [comment]
Belatedly: yup, this is wrong.
