### ISSUE TITLE
Concerning scrollmode

### ISSUE THREAD

**Issue by Wim4rk** [davidgiven/wordgrinder#254]
Hi,
I'm an avid user of Wordgrinder, just love it. I'm now building a small word processor based on an e-ink screen, driven by a Raspberry Pi.
Because of how e-ink updates it would be much better to update the entire page less often. I cloned your repo and started looking for a way to implement this, but found that it's already there. By manually editing my settings-file I could make it work on my PC. I'm not sure how I did it, but somehow the Look and feel-settings has two extra options: scroll mode and palette. Excellent!
Only, now I can't reproduce this on the Raspberry. What am I missing?

**Comment by davidgiven** [comment]
I actually want to build an eink laptop myself --- I already have some of the parts... too many projects, not enough time!

The jump scrolling feature is in the head-of-git version only, so it sounds like you're using the Debian package and so won't have it. You'll need to build your own.

**Comment by Wim4rk** [comment]
Oh, okay, will do. Any idea when this will be released?

(I'm not building a laptop, just a typewriter.)

**Comment by davidgiven** [comment]
It'll be out... eventually? It's just gone through a major refactoring and I want to make sure it's at least mostly stable. There's one remaining bug to fix, with is that spellchecker highlighting doesn't work any more and needs to get fixed.

**Comment by Wim4rk** [comment]
Got it. Tanks a lot for you great work!
