### ISSUE TITLE
Highlighting from end of line with ctrl highlights two words

### ISSUE THREAD

**Issue by quonic** [davidgiven/wordgrinder#26]
Starting from the end of a line I hold Shift+Control and press the left arrow. It highlights two words.

Example: [http://i.imgur.com/GTxmCBV.png](http://i.imgur.com/21WgZRd.png)

The other odd behavior is when trying to highlight to the end of the line. Might be related.

Example: [http://i.imgur.com/21WgZRd.png](http://i.imgur.com/21WgZRd.png)

**Comment by davidgiven** [comment]
You're quite right, those are broken --- thanks. Yes, they're probably both the same issue. I'll have a look.

**Comment by davidgiven** [comment]
Fixed by 5cca44e0b15852de3210458eb6d22f78acb3b239.
