### ISSUE TITLE
Any Explanation as to, Why One Word Scrolls Invisibly Off Right Side Margin?

### ISSUE THREAD

**Issue by rogerxxxx** [davidgiven/wordgrinder#264]
Is there any explanation as to why one word (eg. endless single character, or a word greater than size of column character width, or infinite word length without breaks) scrolls endlessly off the right side margin becoming not viewable?

I'm fluent with type writers, and guessing the left/right scrolling is suppose to mimic a type writers scrolling?

However, if this were the case, why multiple words or characters with spaces inhibit automatic carriage return?

If so, shouldn't there be an explanation of the reasoning within the readme (readme.wg) file?

Also, the numbers along the upper/bottom of text input area, are these appear to be character/column numbers.

**Comment by davidgiven** [comment]
This is when you have one long word on a line, and it's truncated on the right? That's a known bug; I haven't gotten around to fixing it because it's more complicated than it looks (the internal architecture only allows word wrapping between words) and doesn't really come up in real life. You can still edit them, you just can't see the part of the word which extends off the screen.

**Comment by rogerxxxx** [comment]
Your re-description seems to be correct.

Yes.  This is really ugly from a user perspective, not being able to see the text apparently falling-off the right side margin.

One of the most easiest things a child could do when first learning how to use a typewriter, holding down one key and watching to see what happens after constant pressing.  Go figure why us older guys still do this.

I would presume you could just do an initial catch-all for all user input, if char count is >80 chars without spaces, then carriage return after 80 chars; then proceed with processing the usual user input.  But obviously can also easily guess, any programmer would have easily thought of this initial solution or quick workaround!

**Comment by davidgiven** [comment]
Closing for cleanup.
