### ISSUE TITLE
crash in ubuntu 24.04

### ISSUE THREAD

**Issue by lallero7** [davidgiven/wordgrinder#271]
when wordgrinder is opened it crashes giving this error to the terminal

Lua error: [string "src/lua/addons/debug.lua"]:18: bad argument #2 to 'string_format' (number has no integer representation)
stack traceback:
        [C]: in function 'string.format'
        [string "src/lua/addons/debug.lua"]:18: in local 'callback'
        [string "src/lua/events.lua"]:75: in function 'FireEvent'
        [string "src/lua/redraw.lua"]:98: in upvalue 'redrawstatus'
        [string "src/lua/redraw.lua"]:300: in function 'RedrawScreen'
        [string "src/lua/main.lua"]:142: in function 'WordProcessor'
        [string "src/lua/main.lua"]:373: in function 'Main'

**Comment by davidgiven** [comment]
Which version of WordGrinder are you using?

**Comment by davidgiven** [comment]
Closing for cleanup.
