### ISSUE TITLE
Enabling widescreen mode crashes wordgrinder

### ISSUE THREAD

**Issue by starcoat** [davidgiven/wordgrinder#30]
It gives me this exception:

Exception: [string "src/lua/fileio.lua"]:76: attempt to index a nil value (field 'current') [string "src/lua/utils.lua"]:68 [string                       │ 
              │ "src/lua/fileio.lua"]:76 [string "src/lua/fileio.lua"]:132 [string "src/lua/settings.lua"]:18 [string "src/lua/addons/look-and-feel.lua"]:111 [string "src/lua/menu.lua"]:467        │ 
              └─[string "src/lua/menu.lua"]:453 [string "src/lua/menu.lua"]:453 [string "src/lua/menu.lua"]:263 [string "src/lua/navigate.lua"]:608 [string "src/lua/main.lua"]:159 [C]:-1 [string───┘ 
                "src/lua/main.lua"]:185 [string "src/lua/main.lua"]:356                                                                                [string "src/lua/menu.lua"]:453
                                                                                                                                                                                      [string "src/lua/menu.lua"]:453
                                                                                             <press SPACE to continue>                                                                                              [string "src/lua/menu.lua"]:263
                              [string "src/lua/navigate.lua"]:608
(unnamed)[main]                                                  [string "src/lua/main.lua"]:159                                                                                             │ 0 words │ P: 1/1 │ ...
                                                                                                [C]:-1
                                                                                                      [string "src/lua/main.lua"]:185
                                                                                                                                     [string "src/lua/main.lua"]:356

**Comment by davidgiven** [comment]
This is head of git, right? Not a released version?

If so, then yes, that recent commit should have fixed the bug --- please update and try again. I'm afraid it's most likely corrupted and lost your global settings.

Thank you for the bug report. That would have been a nasty one to accidentally release!

**Comment by starcoat** [comment]
Thanks, everything works now!
