### ISSUE TITLE
Feature Request: Non-binary .wg format

### ISSUE THREAD

**Issue by EddyLuten** [davidgiven/wordgrinder#31]
Let me start off by saying that I love WordGrinder, and have been a happy user of it since 0.5.1. I run it very happily on a Raspberry Pi wrangling a CLI-only install of Raspbian.

I also use git to manage my revisions, and while the Markdown exporter is great for being able to diff files, it doesn't offer the convenience of having the entire project in a diffable format. So, I know this may be a tall order but is there any chance of having a non-binary file format for .wg files? Maybe not to replace the existing .wg default, but an additional natively supported format that doesn't require importing and exporting.

Thanks for all the hard work that went into this program, it's helped me tremendously!

**Comment by davidgiven** [comment]
Good news! It's done!

Head of git should have the code in it. It's fully backwards compatible with the old formats, but the only person who's tested it is me, so YMMV. I need to use it for a bit more and see whether it's stable. If you want to try it out, bug reports are welcome. Just be careful.

Yes, a plain text format is such a better idea that I wish I'd had it years ago. I use a VCS too.

**Comment by EddyLuten** [comment]
@davidgiven Hopefully I'll have a chance to try it out tonight or over the weekend. Thanks for the feature!

**Comment by raspbeguy** [comment]
Hello, how do you enable non-binary saving ?
I'd really like to test it, I think binary saving is the only reason I'm not using it for serious stuff.

**Comment by davidgiven** [comment]
Yup --- let me know how it works for you.
