### ISSUE TITLE
Feature request: Import from Markdown

### ISSUE THREAD

**Issue by dw545454** [davidgiven/wordgrinder#34]
The "export to Markdown" feature is wonderful. It would be great to be able to _import_ from a Markdown files as well, to complete the circle!

(I realize that a workaround might be to use Pandoc to convert Markdown-->HTML, then import the html file to Wordgrinder.)

Thanks for considering this!

**Comment by egazz** [comment]
I'd like to second this request.  I use [joplin](https://github.com/laurent22/joplin) for file organization and what-not, and it sends files to whatever text editor you choose.  Unfortunately it does this by sending a temporary file as .md, which Wordgrinder freaks out about.

**Comment by davidgiven** [comment]
It's done! It got merge in #137.
