### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by matthiasbeyer** [davidgiven/wordgrinder#35]
Hi,

I'm trying to package wordgrinder for NixOS ([here](https://github.com/NixOS/nixpkgs/pull/20607)) but I get the following error while building wordgrinder:

```
LINK bin/wordgrinder-debug
TEST tests/apply-markup.lua
Lua error: [string "src/lua/_prologue.lua"]:54: read from undefined local 'loadstring'
stack traceback:
        [C]: in function 'error'
        [string "src/lua/_prologue.lua"]:54: in function '__index'
        [string "src/lua/xpattern.lua"]:27: in main chunk
make: *** [Makefile:470: .obj/lj_n/tests/apply-markup.lua.passed] Error 1
```

Can you help me there?

**Comment by davidgiven** [comment]
That sounds like your Lua 5.2 hasn't been built with the COMPAT option set, which means you're not getting the emulation of the Lua 5.1 functions. WordGrinder uses these for LuaJIT compatibility. (It's been a while, I could be wrong.)

If you've got LuaJIT, try using that instead --- there's an option in the makefile for it. Alternatively, stock Lua 5.1 should work.

The latest version of WordGrinder on github actually reworks this area and may avoid the need for COMPAT; but it's not released yet.

**Comment by matthiasbeyer** [comment]
With lua 5.1 I get:

```
LINK bin/wordgrinder-debug
TEST tests/apply-markup.lua
Lua error: [string "src/lua/_prologue.lua"]:26: attempt to index global 'bit' (a nil value)
stack traceback:
        [string "src/lua/_prologue.lua"]:26: in main chunk
make: *** [Makefile:470: .obj/lj_n/tests/apply-markup.lua.passed] Error 1
```

**Comment by davidgiven** [comment]
Oh, damn, sorry --- bit exists in Lua 5.2 and LuaJIT but not in Lua 5.1. I forgot about that.

Are you willing to patch the version of WordGrinder for the NixOS build? If so it ought to be relatively easy to fix locally. It's effectively the xpattern.lua part of this commit:

https://github.com/davidgiven/wordgrinder/commit/34a45bd83951812019736734604c8238dc8c7a6d

...but I could be wrong (I was last time, after all).

**Comment by matthiasbeyer** [comment]
Sure I will try to get this fixed. I may be slow doing this, so don't think I abandoned it... just a lot to do in my masters courses. Thanks for your support!

**Comment by davidgiven** [comment]
I believe this bug is obsolete.
