### ISSUE TITLE
Error compiling on openSUSE Tumbleweed 

### ISSUE THREAD

**Issue by apinter** [davidgiven/wordgrinder#36]
Hi,

Could use a bit of help here. I try to compile on openSUSE Tumbleweed, but can't get it to work for some reason:

`LINK bin/wordgrinder
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: cannot find -llua5.2
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
collect2: error: ld returned 1 exit status
make: *** [Makefile:317: bin/wordgrinder] Error 1
make: *** Waiting for unfinished jobs....`

Lua52 and lua52-devel is installed and available. Try to reinstall lua as well, but doesn't seems to solve the problem.

**Comment by apinter** [comment]
I tried to install lua from source as well (https://www.lua.org/manual/5.2/readme.html#changes) and also tried on Fedora 25, same unsuccessful result.

**Comment by davidgiven** [comment]
I suspect this is a 64-bit vs 32-bit issue, where the libraries are either installed in the wrong place or the wrong version has been built.

Could you do this and tell me the result, please:

    ls -l /usr/lib/liblua*

**Comment by apinter** [comment]
@davidgiven Sorry for the delay.

`
 ~/Project/git/wordgrinder   master  ls -l /usr/lib/liblua*
-rw-r--r-- 1 root root 223K Oct 27  2016 /usr/lib/liblua.so.5.2
-rw-r--r-- 1 root root 259K Oct 27  2016 /usr/lib/liblua.so.5.3
`
BTW: Output is from the openSUSE Tumbleweed box.

**Comment by davidgiven** [comment]
That sounds like OpenSUSE has installed the library with the wrong name. It should be liblua5.2.so; the language version needs to be part of the library name so that you can choose whether you want Lua 5.2 or 5.3 (or 5.1).

It may be possible to work round this. Try changing the WordGrinder Makefile and change the line which says:

    LUA_LIB ?= -llua5.2

...to:

    LUA_LIB ?= -llua

...and then see if it builds. It's kinda hacky, though, and probably won't work unless you have precisely one version of Lua installed.

**Comment by apinter** [comment]
Unfortunately that didn't work out :/ 

` ~/Project/git/wordgrinder   master ●  make -j   
DEPEND .obj/lj_n/debug-static-x11/src/c/emu/wcwidth.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/lfs/lfs.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/minizip/unzip.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/minizip/zip.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/minizip/ioapi.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/arch/unix/x11/glyphcache.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/arch/unix/x11/x11.d   
SCRIPTS   
DEPEND .obj/lj_n/debug-static-x11/src/c/screen.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/word.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/lua.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/main.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/zip.d   
DEPEND .obj/lj_n/debug-static-x11/src/c/utils.d   
DEPEND .obj/lj_n/debug-x11/src/c/lfs/lfs.d    
DEPEND .obj/lj_n/debug-x11/src/c/minizip/unzip.d   
DEPEND .obj/lj_n/debug-x11/src/c/minizip/zip.d   
DEPEND .obj/lj_n/debug-x11/src/c/minizip/ioapi.d    
DEPEND .obj/lj_n/debug-x11/src/c/arch/unix/x11/glyphcache.d   
DEPEND .obj/lj_n/debug-x11/src/c/arch/unix/x11/x11.d    
DEPEND .obj/lj_n/debug-x11/src/c/screen.d   
DEPEND .obj/lj_n/debug-x11/src/c/word.d    
DEPEND .obj/lj_n/debug-x11/src/c/lua.d   
DEPEND .obj/lj_n/debug-x11/src/c/main.d    
DEPEND .obj/lj_n/debug-x11/src/c/zip.d   
DEPEND .obj/lj_n/debug-x11/src/c/utils.d   
DEPEND .obj/lj_n/release-x11/src/c/lfs/lfs.d   
DEPEND .obj/lj_n/release-x11/src/c/minizip/unzip.d   
DEPEND .obj/lj_n/release-x11/src/c/minizip/zip.d   
DEPEND .obj/lj_n/release-x11/src/c/minizip/ioapi.d   
DEPEND .obj/lj_n/release-x11/src/c/arch/unix/x11/glyphcache.d   
DEPEND .obj/lj_n/release-x11/src/c/arch/unix/x11/x11.d   
DEPEND .obj/lj_n/release-x11/src/c/screen.d   
DEPEND .obj/lj_n/release-x11/src/c/word.d   
DEPEND .obj/lj_n/release-x11/src/c/lua.d   
DEPEND .obj/lj_n/release-x11/src/c/main.d    
DEPEND .obj/lj_n/release-x11/src/c/zip.d   
DEPEND .obj/lj_n/release-x11/src/c/utils.d   
DEPEND .obj/lj_n/debug-static/src/c/emu/wcwidth.d   
DEPEND .obj/lj_n/debug-static/src/c/lfs/lfs.d   
DEPEND .obj/lj_n/debug-static/src/c/minizip/unzip.d   
DEPEND .obj/lj_n/debug-static/src/c/minizip/zip.d   
DEPEND .obj/lj_n/debug-static/src/c/minizip/ioapi.d   
DEPEND .obj/lj_n/debug-static/src/c/arch/unix/cursesw/dpy.d   
DEPEND .obj/lj_n/debug-static/.obj/lj_n/luascripts.d   
DEPEND .obj/lj_n/debug-static/src/c/screen.d   
DEPEND .obj/lj_n/debug-static/src/c/word.d   
DEPEND .obj/lj_n/debug-static/src/c/lua.d   
DEPEND .obj/lj_n/debug-static/src/c/main.d   
DEPEND .obj/lj_n/debug-static/src/c/zip.d   
DEPEND .obj/lj_n/debug-static/src/c/utils.d   
DEPEND .obj/lj_n/debug/src/c/lfs/lfs.d   
DEPEND .obj/lj_n/debug/src/c/minizip/unzip.d   
DEPEND .obj/lj_n/debug/src/c/minizip/zip.d   
DEPEND .obj/lj_n/debug/src/c/minizip/ioapi.d   
DEPEND .obj/lj_n/debug/src/c/arch/unix/cursesw/dpy.d   
DEPEND .obj/lj_n/debug/.obj/lj_n/luascripts.d   
DEPEND .obj/lj_n/debug/src/c/screen.d   
DEPEND .obj/lj_n/debug/src/c/word.d   
DEPEND .obj/lj_n/debug/src/c/lua.d   
DEPEND .obj/lj_n/debug/src/c/main.d   
DEPEND .obj/lj_n/debug/src/c/zip.d    
DEPEND .obj/lj_n/debug/src/c/utils.d    
DEPEND .obj/lj_n/release/src/c/lfs/lfs.d    
DEPEND .obj/lj_n/release/src/c/minizip/unzip.d   
DEPEND .obj/lj_n/release/src/c/minizip/zip.d    
DEPEND .obj/lj_n/release/src/c/minizip/ioapi.d    
DEPEND .obj/lj_n/release/src/c/arch/unix/cursesw/dpy.d    
DEPEND .obj/lj_n/release/.obj/lj_n/luascripts.d    
DEPEND .obj/lj_n/release/src/c/screen.d    
DEPEND .obj/lj_n/release/src/c/word.d   
DEPEND .obj/lj_n/release/src/c/lua.d   
DEPEND .obj/lj_n/release/src/c/main.d    
DEPEND .obj/lj_n/release/src/c/zip.d   
DEPEND .obj/lj_n/release/src/c/utils.d    
DEPEND .obj/lj_n/debug-static-x11/.obj/lj_n/luascripts.d   
DEPEND .obj/lj_n/debug-x11/.obj/lj_n/luascripts.d    
DEPEND .obj/lj_n/release-x11/.obj/lj_n/luascripts.d    
CC .obj/lj_n/release/src/c/utils.o    
CC .obj/lj_n/release/src/c/zip.o    
CC .obj/lj_n/release/src/c/main.o    
CC .obj/lj_n/release/src/c/word.o    
CC .obj/lj_n/release/src/c/lua.o    
CC .obj/lj_n/release/src/c/screen.o    
CC .obj/lj_n/release/.obj/lj_n/luascripts.o   
In file included from src/c/zip.c:6:0:    
src/c/globals.h:38:17: fatal error: lua.h: No such file or directory   
 #include <lua.h>   
                 ^   
compilation terminated.    
make: *** [Makefile:325: .obj/lj_n/release/src/c/zip.o] Error 1    
make: *** Waiting for unfinished jobs....     
In file included from src/c/utils.c:6:0:     
src/c/globals.h:38:17: fatal error: lua.h: No such file or directory   
 #include <lua.h>   
                 ^   
compilation terminated.   
In file included from src/c/main.c:9:0:   
src/c/globals.h:38:17: fatal error: lua.h: No such file or directory   
 #include <lua.h>    
                 ^    
compilation terminated.   
make: *** [Makefile:325: .obj/lj_n/release/src/c/utils.o] Error 1   
make: *** [Makefile:325: .obj/lj_n/release/src/c/main.o] Error 1   
In file included from src/c/word.c:6:0:   
src/c/globals.h:38:17: fatal error: lua.h: No such file or directory    
 #include <lua.h>    
                 ^    
compilation terminated.   
In file included from src/c/lua.c:6:0:   
src/c/globals.h:38:17: fatal error: lua.h: No such file or directory   
 #include <lua.h>   
                 ^   
compilation terminated.   
make: *** [Makefile:325: .obj/lj_n/release/src/c/word.o] Error 1   
make: *** [Makefile:325: .obj/lj_n/release/src/c/lua.o] Error 1   
In file included from src/c/screen.c:6:0:   
src/c/globals.h:38:17: fatal error: lua.h: No such file or directory   
 #include <lua.h>   
                 ^   
compilation terminated.   
make: *** [Makefile:325: .obj/lj_n/release/src/c/screen.o] Error 1   
In file included from .obj/lj_n/luascripts.c:1:0:   
src/c/globals.h:38:17: fatal error: lua.h: No such file or directory   
 #include <lua.h>   
                 ^   
compilation terminated.   
make: *** [Makefile:325: .obj/lj_n/release/.obj/lj_n/luascripts.o] Error 1   
`    

Thinking of compiling a package on Debian probably and will take it from there. If you have further ideas that is more than welcome! 
Love Wordgrinder and would love to get it run on my Suse and Fedora boxes.

**Comment by apinter** [comment]
Ok, little correction to the above. After installing the lua52-devel packages it compiles with the modified Makefile... Sorry about this, had to reinstall my system a few days ago and been missing out some packages.
Now it compiles and it is installed, but when I try and run wordgrinder it is missing lfs.

``` 
 ~/Project/git/wordgrinder   master ●  wordgrinder 
Lua error: [string "src/lua/_prologue.lua"]:18: module 'lfs' not found:
	no field package.preload['lfs']
	no file '/usr/share/lua/5.2/lfs.lua'
	no file '/usr/share/lua/5.2/lfs/init.lua'
	no file '/usr/lib64/lua/5.2/lfs.lua'
	no file '/usr/lib64/lua/5.2/lfs/init.lua'
	no file './lfs.lua'
	no file '/usr/lib64/lua/5.2/lfs.so'
	no file '/usr/lib64/lua/5.2/loadall.so'
	no file './lfs.so'
stack traceback:
	[C]: in function 'require'
	[string "src/lua/_prologue.lua"]:18: in main chunk
```
Very hackish, but let's see how it turns out.

**Comment by apinter** [comment]
Got the solution for installing on openSUSE. As @davidgiven mentioned must modify the Makefile and make sure that have all the dependencies installed. The problem is with lua only in this case. From lua I have installed the following packages:

- lua-luafilesystem
- lua
- lua-devel
- liblua5_3
- liblua5_3-32bit

David listed in the README the remaining dependencies.
After all this can compile and install without problem.

Thanks for your help @davidgiven , closing issue.

![image](http://i65.tinypic.com/2v2tggo.png)

**Comment by davidgiven** [comment]
That's awesome, thanks! Looks good with that font, too, although I'm not sure I remember designing the screen in the top right...

The dependency issues remain a constant annoyance. I'm wondering about bundling the relevant dependencies into the distribution package. They won't be usable in official packages due to the requirement on using the distribution's copy of libraries, but they should make building from source easier.

**Comment by apinter** [comment]
Actually was just thinking to compile into an rpm for openSUSE and Fedora and drop it to OBS. Need to find the time, but will totally do this. Too awesome piece of software to get stuck with dependencies ;)
