### ISSUE TITLE
`DESTDIR` / `PREFIX` doesn't seem to work?

### ISSUE THREAD

**Issue by avindra** [davidgiven/wordgrinder#41]
I've tried [numerous configurations](https://build.opensuse.org/package/revisions/home:avindra/wordgrinder) of `DESTDIR` and `PREFIX` when trying to build this for openSUSE Tumbleweed, but nothing seems to work.

`make install` is putting files into the home directory by default.

I think this might be related to the recent switch to the ninja build system. Perhaps the options aren't being passed through?

**Comment by davidgiven** [comment]
Yes, there's a bug there --- sorry. What's happening is that the values of `DESTDIR` and `PREFIX` are baked in when the ninjafile is generated. So if you do the traditional:

    $ make
    $ make install PREFIX=...

...then the value of `PREFIX` is ignored because the ninjafile was generated at the previous step.

This needs to be fixed, but for now the workaround is:

    $ make clean
    $ make all PREFIX=...
    $ make install PREFIX=...

**Comment by avindra** [comment]
Sounds good, I'll give that a shot later. Thanks!

**Comment by avindra** [comment]
That worked:

https://build.opensuse.org/package/rdiff/home:avindra/wordgrinder?linkrev=base&rev=13

Thanks. I'll close out this issue for now as the build is working.

If you could shoot me a quick note here, I'll gladly test any `Makefile` changes for ya for openSUSE.

**Comment by davidgiven** [comment]
Thanks --- I will.

**Comment by avindra** [comment]
@davidgiven : This still seems to be a problem with 0.7 and 0.7.1

**Comment by avindra** [comment]
@davidgiven Closing again.

The workaround you mentioned on Aug 14 still works. So I'll just submit the package for openSUSE that way

**Comment by ItchyBugReporter** [comment]
This bug still exists in 0.7.2, however the workaround still works.

**Comment by ryandesign** [comment]
Please reopen this bug because it still has not been fixed as of version 0.8. The build system should honor the value of `DESTDIR` that is set at `make install` time.
