### ISSUE TITLE
Previous lines don't display in tmux

### ISSUE THREAD

**Issue by kronos29296** [davidgiven/wordgrinder#43]
I use tmux 2.5 in zsh. When I typed a line in wordgrinder and pressed enter to the next line there is no problem. But if I navigate to the previous line the text is invisible and the previous lines preview are not updating either.

First I typed a line on the first line and then some text on the second line in tmux using word grinder.
![screenshot from 2017-08-23 16-05-00](https://user-images.githubusercontent.com/10050325/29611957-44c8d7be-881d-11e7-8a4b-87ebc248b919.png)

But when i press up arrow to go to the first line it doesn't get updated.
![screenshot from 2017-08-23 16-05-03](https://user-images.githubusercontent.com/10050325/29611960-486b5626-881d-11e7-87e9-e0bcc155579e.png)

This issue does not occur in normal gnome-terminal but happens only in tmux.

**Comment by davidgiven** [comment]
That sounds like a terminal type problem with tmux --- you're not getting the Unicode banner, either. Could you check that tmux is setting the TERM environment variable to something sensible?

**Comment by kronos29296** [comment]
It is set as xterm-256color. This is so that true colors are displayed properly in vim.

**Comment by davidgiven** [comment]
Can you enter unicode in vim running in tmux?

**Comment by kronos29296** [comment]
I use vim airline with patched fonts which display correctly and checked unicode by typing lamda within tmux. I use byobu with tmux which is a set of python scripts with a status bar for tmux.

I have nailed down the issue.
This line is the offending config in tmux.conf.

`set -g default-terminal "xterm-256color"`

It was originally added to get true colors working but is not needed now. Removing the line fixed wordgrinder.

So I'll close this issue and Thank You.

**Comment by davidgiven** [comment]
Awesome --- thanks for the report!
