### ISSUE TITLE
Flickering while typing

### ISSUE THREAD

**Issue by marcobelloneon** [davidgiven/wordgrinder#45]
In version 0.6 and 0.7 I experience a persistent flickering of the typing line and status bar while typing. It seems like a strange effect connected to their refreshing, that causes them to blink.

It is mostly notable when I press and keep pressed a key, but it also happens randomly while typing any word at any typing speed. The flickering interests just the status bar and the line where I'm currently typing, but I can't recognize a pattern. Sometimes the whole line flickers, sometimes just a few words, sometimes just the word i'm typing, sometimes both the line and the status bar.

I'm running it on Windows 10 and I tried various compatibility modes (all of them) and the issue is still there. I tested it with an unmodified installation, then I tried to change the font, fullscreen the application and launch the program as administrator. None of this solves the issue.

I made a [very rough video](https://mega.nz/#!omJFGCxZ!YH-Yil9WYJwpKFmSrr3wNdFIEoiCv16rEkXwJD9zrAY) with my cell phone because I'm not sure a recording program for the desktop will record this fast flickering.

It it can be of any help, I tried copy-pasting a lot of text, at the point where the whole application would be really slow, with a delay of some seconds between the pressing of the key and its appearance on the screen (this probably opens another issue of its own), and in this particular circumstance the flickering totally disappears.

**Comment by davidgiven** [comment]
I see the occasional flicker at my end, but nothing nearly as bad as you're seeing.

I'm generally unhappy with the Windows graphics performance, and it needs an overhaul --- it's very slow. I'm not really a Windows coder, as you may be able to tell... adding double buffering out to be a fairly straightforward fix, though. The only worry is that it might make performance even worse.

What's your machine spec, by the way?

I'm curious about the cut-and-paste issue you mention. Can you expand?

**Comment by marcobelloneon** [comment]
Sorry, I expressed myself poorly.
I made a test yesterday and in a big document with lots of words (60.000) I experienced a lot of latency between the input from the keyboard and the appearence of the characters on the screen. I also found that there wasn't any flickering with this latency. But this was in version 0.6, I just tried 0.7 and even with more words there isn't any latency and the flickering is still there.

I run Windows 10 Pro 64-bit on a desktop computer with AMD FX-4100, 8,0GB RAM and AMD Radeon HD 6570.

**Comment by davidgiven** [comment]
That's weird but... good that it's fixed in 0.7? WordGrinder's _supposed_ to be able to deal with large documents, and I've had reports of people using 0.6 and 0.5 with 300,000 word files, so it's a bit odd you were having problems.

I've a look at fixing the flicker, but I can't promise anything soon (due to other stuff happening in November).

**Comment by davidgiven** [comment]
I haven't forgotten! Or rather, github hasn't forgotten.
