### ISSUE TITLE
Stripping debuginfo

### ISSUE THREAD

**Issue by funnelfiasco** [davidgiven/wordgrinder#46]
In the Fedora package, I patched the makefile to add `CFLAGS=-g` in order to build the debuginfo package. But it looks like that setting no longer gives the desired result, since rpmbuild now complains:
`Empty %files file /builddir/build/BUILD/wordgrinder-0.7.1/debugsourcefiles.list`

Is the ninja script stripping out the debug symbols at build time and if so is there any way to disable it?

**Comment by davidgiven** [comment]
The executables are explicitly stripped on installation --- it never occurred to me anyone wanted the unstripped versions...

I've added a setting, but it won't help for 0.7.1. Does Fedora allow patching build trees the way Debian does?

Incidentally, as part of 0.7.1, it's now possible to build WordGrinder using entirely external dependencies (other than xpattern); Debian wanted this. So you can now use external minizip, luafilesystem, etc. This might be useful for Fedora. The syntax is a bit funky, but essentially you pass in to the makefile:

```
        PREFIX=/usr \
        DESTDIR=debian/tmp \
        OBJDIR=.obj \
        LUA_PACKAGE=lua-5.3 \
        LUABITOP_PACKAGE="--cflags={} --libs={}" \
        LUAFILESYSTEM_PACKAGE=lua5.3-filesystem \
        MINIZIP_PACKAGE=minizip \
        UTHASH_PACKAGE="--cflags={} --libs={}" \
        LUA_INTERPRETER=/usr/bin/lua5.1 \
        CFLAGS="$(CPPFLAGS) $(CFLAGS)" \
        LDFLAGS="$(LDFLAGS)" \
```

Anything ending in _PACKAGE takes either a pkgconfig name or an explicit set of flags.

**Comment by funnelfiasco** [comment]
Looks good. I'll carry that commit as a patch in the Fedora build for this release and drop it for the next release. (And as an aside, the way the Fedora packaging works, the debuginfo gets stripped and split into a separate RPM after the binaries are all built. So we're still shipping stripped binaries, we just strip them in a different place in the process)
