### ISSUE TITLE
Build issues in Ubuntu 17.10

### ISSUE THREAD

**Issue by oaguy1** [davidgiven/wordgrinder#47]
First off, I really enjoy writing in wordgrinder. I installed it on my work MacBook Pro and have been using it for all serious writing. I enjoyed it so much I wanted to build it on my personal Ubuntu 17.10 laptop. After downloading the required packaged via apt-get and decompressing the source archive, I `cd`'d into the wordgrinder-0.7.1 directory and tried to use `make`. I got the error:
```
ninja: error: unknown target 'all', did you mean 'dev'?
Makefile:96: recipe for target 'all' failed
make: *** [all] Error 1
```
Just for fun, I also tried `make install`, which returned the error:
```
make: *** No rule to make target 'install'.  Stop.
```
and also `make dev`, which returned:
```
ninja: no work to do.
```
I tried this on the source archives for both 0.7.1 and 0.7 with the same result. I was successfully able to build version 0.6, but the document I need to working on was written on my work machine using version 0.7. Is there anything I am missing?

**Comment by davidgiven** [comment]
Thank you for the kind words!

What this probably means is that it hasn't found a critical library, which in turn probably means that the documentation about the required dependencies is wrong. I'm setting up a 17.10 device to test on, but it's being annoyingly slow and I probably won't get to it today.

If you still have it, could you paste the entire build log (particularly the bit at the top where it says 'Detecting...')?

**Comment by davidgiven** [comment]
Everything seems fine on my machine, so I suspect that the build system's got itself into a twist somehow. Could you try:

    make clean
    make all

...and let me know what happens?

**Comment by oaguy1** [comment]
Wow, it worked just fine this time. Sorry for the wild goose chase. I like coding in lua, happy to chip in some help if you ever need!

**Comment by davidgiven** [comment]
Fair enough, closing. (The only thing better than a good bug report is a good bug report that turns out to be a red herring, because that involves doing no work.)

I'm aware the build system is a bit problematic, and I'm going to have to change it. Again.

Thank you for using WordGrinder --- feel free to file issues if you have any comments and/or suggestions!
