### ISSUE TITLE
Method to disable testing

### ISSUE THREAD

**Issue by abenson** [davidgiven/wordgrinder#53]
When trying to cross-build wordgrinder I have no way of testing it on the host, is there a way to disable the testing during compilation?

**Comment by davidgiven** [comment]
Yes, but it's a bit baroque. You have to create the ninjafile then manually invoke it to produce your binaries.

> make /tmp/wg-build/build.ninja
> ninja -f /tmp/wg/build/build.ninja bin/xwordgrinder-builtin-x11-release

(Replace with whatever other binary name you want to make.)

This is something which it should be possible to do out-of-the-box; I'll add support.

**Comment by davidgiven** [comment]
Okay, that was easy. Try this from head of git:

> make install-notests
