### ISSUE TITLE
Direct Printing

### ISSUE THREAD

**Issue by abenson** [davidgiven/wordgrinder#54]
Could there be an option to print PostScript to `lp` or something?

**Comment by davidgiven** [comment]
Sorry, generating PostScript is out of scope for WordGrinder. The suggested way to print is to export to troff or LaTeX, typeset it to PostScript, and then print that.

```
wordgrinder --convert MyDocument.wg temp.tr
groff -ms temp.tr > temp.ps
evince temp.ps
```

**Comment by abenson** [comment]
I wrote a [helper script](https://gist.github.com/abenson/87642857d754b670983f9f8cd1647945#file-wg2ps) to do this for me. It's not direct printing, but it does automate it! Hope it helps.
