### ISSUE TITLE
Feature requests: en dashes, indentation of the first line of the paragraph and text align

### ISSUE THREAD

**Issue by hmslima** [davidgiven/wordgrinder#55]
First of all, I have to thank you David because you created the almost-perfect word processor for me, I say almost because there are some features that I need a lot, they're really **essential** for me.

**En dashes**

In LibreOffice and Latex I just have to type two traces (--) to have an en dash (–). Surely it's possible in WordGrinder since we can convert "" to “” even diuring the typing, it's only necessary apply the same process to --.

Seems that English-speaking people only uses quotation marks to show the speaking of the characters, but Portuguese-speaking people and Spanish-speaking people use dashes *(apparently Spanish-speakers use em dashes(—)  if I consider the Spanish-written books that I have here, but, as brazilian, I use en dashes (–))*.

**indentation of the first line of the paragraph**

Most first lines of my paragraphs are indented. Why you don't allow the use of TAB to make an identation like we do in LibreOffice/MicrosoftOffice? The indentation provided by wordgrinder, which indents the whole paragraph, is useful for technical texts and source-codes, but not much for novels.

Normal paragraph in WordGrinder
> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

The indentation I want
>    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

This type indentation occurs in English-written texts too.

_I was thinking, instead of putting a TAB-space in each paragraph, a great useful feature you could add to WordGrinder is a text-configuration file, where we define the formattation of the document. During the exportation this file would be transformed to:_

- _a .css file for the .html file_
- _the styles.xml file within the .odt document_
- _a .sty file for the .tex file_

**Text align**

It's very important thing for me, especially the centring. I know that we must focus in writting, but it is a thing that I need already in my base files.

.
.

With the exception of Latex, no other markup language has these features, that's why I am stuck in LibreOffice. 
P.S.: I don't like Latex very much.

.
.

I hope these features can be implemented.

**Comment by davidgiven** [comment]
Argh, sorry for the delay --- I did actually write a response, but forgot to hit send...

The bad news is: the features you've asked for won't work with WordGrinder.

The reasons are:

- em and en dashes: WordGrinder uses a fixed-pitch font. This means that while this could be implemented, hyphens, en and em dashes (and minus signs) would look almost identical on the screen, which is almost certainly not what you want. What I do is to use double and triple hyphens (-- and ---) to represent en and em dashes. They look more or less right, and can be converted to the real thing very easily at the typesetting stage. (I think LaTeX will do it automatically.) I've written prose using the em-dash conversation convention you mention (it's used in English too, rarely) and it works reasonably well.

- Indentation and centring: WordGrinder doesn't know _anything_ about formatting. This is deliberate; the intention of the application is to make me focus on the text and not the style. The way it shows text on the screen is wholly unrelated to how text appears on the printed page. You're supposed to export the finished document into a real typesetting package and format it there, and only then make decisions about how it's supposed to look.

That said, there are two distinct ways in which WordGrinder can show your text --- the default, with spaces between paragraphs, and dense mode, which removes the spaces and indents paragraphs. This may be what you're looking for. Bear in mind that this is a UI thing only and is not stored in the document (it's a system wide setting). See File -> Global Settings -> Change look and feel -> Use dense paragraph layout.
