### ISSUE TITLE
Feature request: move some doc-specific preferences to global

### ISSUE THREAD

**Issue by egazz** [davidgiven/wordgrinder#57]
I find myself having to change certain things every time I open a new doc.  It's mainly stylistic, such as smart quotes, and it'd be nice if this (plus autosave, toggling the status bar, etc.) were things that I could set once and then not have to keep changing every time I start a new file.

**Comment by davidgiven** [comment]
I'd rather not do this --- I tend to have these set differently for various documents depending on what I'm doing with them (blog post, prose, etc).

I do realise it's an issue, though. I'm considering adding support for templates, or at least _a_ template, so you can configure the settings in the default new document. This would probably work by having a File -> Set Startup Document which takes a copy of the current document; File -> New would then take a copy of this.

Would this meet your use case?
