### ISSUE TITLE
Bug: File selector does not reflect UI upon first opening

### ISSUE THREAD

**Issue by wwtex** [davidgiven/wordgrinder#59]
If no arrow keys are pressed before pressing `return` in the open file dialogue, the file WordGrinder attempts to open won't reflect what's selected.

![wordgrinder-bug](https://user-images.githubusercontent.com/39504770/40335932-3abe5914-5d1b-11e8-9b8d-0bcfa3d20862.gif)

The expected behavior would be that the file dialogue goes up a directory, as `..` is what's selected in the dialogue.

**Comment by davidgiven** [comment]
Yeah, there are issues with the file selector state machine. It needs a redesign.

This is not a trivial fix; the reason why it's trying to open '' is that if you immediately press RETURN it will use the filename preentered in the text box (which is empty in this case). This is done so you can do File -> Save As and get the current filename ready to go.

File selection state machines are hard.
