### ISSUE TITLE
Opening old (0.6.3) binary documents with latest version throws error, erases file

### ISSUE THREAD

**Issue by Jachimo** [davidgiven/wordgrinder#60]
After building the latest (4aa462e050e0d191e89b298b55ceb7db40e3ae26) version on MacOS, I attempted to open a file created with version 0.6.3 (Debian Stable package, on Linux system), and it attempted to upgrade the document set to the new text-based format from the binary. When I tried to save, it throws an error and nothing is written. On quit, the file is now zero bytes long and the previous contents are deleted. If a backup has not been made, the potential seems to exist for the user to lose their document.

A text file with detailed information is attached, but the error received on save is: 

`Exception: [string "src/lua/fileio.lua"]:146: invalid value (table) at index 580 in table for 'concat' [string "src/lua/utils.lua"]:68 [C]:-1 [string "src/lua/fileio.lua"]:146 (tail call):-1 [string "src/lua/fileio.lua"]:193 (tail call):-1 (tail call):-1 [string "src/lua/main.lua"]:184 [C]:-1 [string  "src/lua/main.lua"]:194 [string "src/lua/main.lua"]:365 `

It may or may not be relevant that the 0.6.3 file was checked into Git and then retrieved (binary mode) to move it from the Linux to MacOS system.

More complete walkthru of test procedure: [wordgrinder-issue.txt](https://github.com/davidgiven/wordgrinder/files/2150304/wordgrinder-issue.txt)

**Comment by Jachimo** [comment]
I have tried to replicate this via a trivial file (so I could upload it) but unfortunately cannot. Very simple files created with either 0.5.1 (Debian Jessie) or 0.6.3 (Debian Stretch) seem to open and can be saved just fine in the latest version. However, the significantly longer and more complex document I had (but cannot upload) fails repeatedly. I have tried creating test documents with various levels of headers, Unicode characters, etc., and I am not sure what is triggering the inability to save the converted version.

**Comment by davidgiven** [comment]
That's very bad. Would you be willing to send me the more complex document privately so I can try it? This needs fixing.

**Comment by Jachimo** [comment]
I sent you a minimal test file that seems to exhibit the behavior. It is not every file, just one specific one, but I can't tell what makes it different or weird.

**Comment by davidgiven** [comment]
Fixed.

The reason it was so hard to reproduce is that this only affected text in the clipboard when the original doc was saved. If there wasn't any, or you selected something in the new doc before saving (so replacing the contents of the clipboard), everything would be fine.

Thank you for finding this! It's good to get it fixed.

**Comment by davidgiven** [comment]
The data loss protection fix was significantly less fixed than I thought. In fact, it made it impossible to save files under some circumstances.

Please check out head and try again?

**Comment by Jachimo** [comment]
Couldn't replicate the issue using the latest HEAD (6ecc254) and also didn't notice any regressions either (although to be fair, I didn't notice them using bcbfbab1 either).

**Comment by davidgiven** [comment]
Regressions people don't notice are the best kind of regression.

Let me know if you spot any problems...
