### ISSUE TITLE
Vim Key Bindings

### ISSUE THREAD

**Issue by Immortalin** [davidgiven/wordgrinder#61]

**Comment by davidgiven** [comment]
Not currently on the agenda.

While I wrote most of WordGrinder using vim, I don't think it's suitable for prose. There are some things which don't map well (what do j and k do --- move a line or a paragraph?) and I've used enough mostly-complete vim keymap implementations to know just how frustrating a mostly-complete implementation can be. So I'm not going to work on this. Sorry.

That said, I'm open to pull requests if you can make it work...
