### ISSUE TITLE
Feature request: Footnotes

### ISSUE THREAD

**Issue by mshefa** [davidgiven/wordgrinder#63]
Dear Mr. Given,

I am a HUGE fan of WordGrinder. In fact, I think it’s the best new thing since the invention of the printing press. (Just kidding, but I do love it so very much.).

I was wondering if you had ever considered adding footnote support, small caps support, and support for exporting to RTF. I know WG is supposed to be as minimal as can be, but, as a legal writer, not being able to have footnotes especially means I can’t use this academically and professionally (I so want to!!). Think of all the kids who could use this for class papers! I am sure many people (in the legal and scientific fields) would be THRILLED if that functionality were added.

Not only is WG super gorgeous in its simplicity, but it helps me get the job done without distraction. Thank you for your excellent and necessary contribution to society.

Would love to hear from you!

Sincerely,

A humble WG fan

**Comment by davidgiven** [comment]
Hello ---

Thank you for the kind words; unfortunately, footnotes aren't on the todo list right now --- they're surprisingly complicated to implement, as each footnote is effectively its own document. It may be possible to implement some kind of hyperlink feature where footnotes can reference other WordGrinder documents in the document set, but that then makes import and export much more complicated and difficult to define. I do want a feature like this at some point (apart from anything else I want to be able to write HTML hyperlinks easier) but it'll need to be very carefully planned and specified.

Re RTF support: there is actually a WIP RTF exporter. Unfortunately the RTF specification is so fuzzy that I have no idea whether it's correct or not! And when I tried importing the RTFs into OpenOffice, really weird things happened, so I haven't enabled it. I'm still looking for a way to propertly test this... (See #64.)

**Comment by mshefa** [comment]
Thanks for the response! Have you checked out how emacs in org-mode handles footnotes? I don’t believe it uses a new buffer. It basically links to a section of the document with a Footnotes header. Then when the WG document is exported, the footnotes can be reorganized to be actual bottom-of-the-page footnotes. Just thought it was worth mentioning. Thanks again for WordGrinder.
