### ISSUE TITLE
Special characters in filenames

### ISSUE THREAD

**Issue by nrosvall** [davidgiven/wordgrinder#67]
Hi,

Thanks for the great program. I'm using it on Windows for writing a book. It's works perfectly for my needs, however there's a small issue with filenames when using Scandinavian characters such as "ä" or "ö".

 It's a minor problem really as it's simply cosmetic. I think Wordgrinder should use different encoding for filenames to support special characters. In Wordgrinder save file dialog the filename displays ok, but Windows does not display those special characters when the file is save from Wordgrinder.

If I rename the file manually (to include those Ä and Ö characters) from Windows explorer, Wordgrinder
does not display them correctly but replaces them with what seems to be random junk.

Cheers!

**Comment by davidgiven** [comment]
Very belatedly (I'm working through the backlog), this is true. Unfortunately the standard Windows file system API expects ANSI encoded filenames, and making it use Unicode is extremely non-trivial. I'm having a look, but I can't promise anything.
