### ISSUE TITLE
Minor typo in "Paragraph Syles" menu ("test" instead of "text")

### ISSUE THREAD

**Issue by dw545454** [davidgiven/wordgrinder#69]
To reproduce: 

- Open a document in Wordgrinder. 
- Press CTRL+P to open Paragraph Styles menu. 
- The first option reads `0 P: Plain test` instead of what I'm assuming should be `0 P: Plain text`.

It's very minor, but I wanted to let someone know. Thanks for this amazing program!

**Comment by dw545454** [comment]
Thank you for your reply, David.

The File->About dialog box reports: `WordGrinder 0.7.1` / `© 2007-2013 David Given` / `File format version 7.0`. So it does look like I was using an older version.

But that's enough "cat vacuuming" for now... I should probably get back to writing! Thank you once again for Wordgrinder and also for keeping it open source.

**Comment by davidgiven** [comment]
Yes, please upgrade! Apart from anything else there's a nasty crashing bug in 0.7.1 which I'd rather you didn't run in to. (I will point out that the copyright date is wrong --- in, I now see, in both versions!)
