### ISSUE TITLE
Feature request: Word count of highlighted section

### ISSUE THREAD

**Issue by semioticrobotic** [davidgiven/wordgrinder#71]
I love the fact that Wordgrinder displays a document's overall word count at the bottom of the screen. I'd love if it could also show me the word count of _just a single section_ of highlighted text, too.

This is a fairly common use case for me as I am composing documents with a specific word limit. That document might contain some spare notes, jotted quotations, or references—all in addition to the actual prose sentences I'm drafting. So Wordgrinder's word count doesn't actually tell me the length of the document I've _written_; it tells me the length of the entire document (my text, plus notes, plus links, plus quotations, etc.). I'd love if I could (fairly quickly or at a glance) determine the word count of a specific section of a document.

**Comment by davidgiven** [comment]
I have actually wondered about this; it's slightly more complicated than it looks due to having to sum partial paragraphs. There is however a basic workaround: copy, paste into new subdocument, look at word count, delete subdocument. It could be improved, though.

One thing I've thought about is a hierarchical word count in the contents page. So, for each section you'd see the total count of each section plus enclosed sections. That should be very easy as all the information is precomputed. Does this fit your requirements?

**Comment by semioticrobotic** [comment]
It _might_, but to be honest I think I'd need to see it in action to make a determination. My ideal solution wouldn't take me too far "out" of the writing (one of the reasons your proposed workaround, while clever and certainly effective, doesn't appeal to me). In other applications (e.g., Gedit), I can simply highlight a few paragraphs, press Alt + T + D, see the numbers, hit Esc, and keep writing—don't even need to leave the keyboard (ideal!).

**Comment by davidgiven** [comment]
If you want to try out the prototype and you're happy with building a copy yourself, try the version in the `wordcounts` branch --- word counts are shown in the table of contents dialogue (Edit -> Go To).

**Comment by semioticrobotic** [comment]
Unfortunately that's beyond my ken (sorry!), but I trust it's awesome and look forward to using it, should it indeed make it into the next version!

**Comment by davidgiven** [comment]
No worries --- here's a screenshot. I'm not entirely convinced about the formatting but putting the counts anywhere else renders the list unreadable. I'm going to play with that a bit.

![image](https://user-images.githubusercontent.com/100638/50780906-0899b500-129c-11e9-97d5-2a821aad89fe.png)

**Comment by davidgiven** [comment]
Very belatedly: it's actually about three lines of code to display the word count of the selected text when citing to the clipboard (as the clipboard already had the functionality for tracking this), so I'll do that.
