### ISSUE TITLE
Package new version for Fedora repositories

### ISSUE THREAD

**Issue by semioticrobotic** [davidgiven/wordgrinder#72]
The Fedora repositories contain version [0.7.1](https://github.com/davidgiven/wordgrinder/releases/tag/0.7.1), which contains a significant bug that leads to crashes. Version [0.7.2](https://github.com/davidgiven/wordgrinder/releases/tag/0.7.2) should be made available.

Might be a request better directed at @funnelfiasco.

**Comment by funnelfiasco** [comment]
Oops! How'd I miss that there's a new release? I'll work on getting this packaged. In the future, if it's just a matter of getting a new release into the repo, [bugzilla.redhat.com](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=wordgrinder) (or arguablly https://src.fedoraproject.org/rpms/wordgrinder)  is probably the right place to raise a ticket.

I've opened https://bugzilla.redhat.com/show_bug.cgi?id=1663549
@davidgiven, you can close this issue

**Comment by davidgiven** [comment]
Thanks!

TBH, I'd completely forgotten you were looking after the rpm package. Is there any automation I can put into place to notify something of a new release?

**Comment by funnelfiasco** [comment]
I have it set up on release-monitoring.org but I think the notifications on that are broken currently. So hopefully that will be fixed shortly and it won't be an issue in the future.

**Comment by semioticrobotic** [comment]
I'm okay to close this now, seeing as we seem to have a workflow set up!

**Comment by davidgiven** [comment]
Thanks very much for doing this.
