### ISSUE TITLE
Follow XDG spec for settings file

### ISSUE THREAD

**Issue by retiform** [davidgiven/wordgrinder#73]
The code found here

https://github.com/davidgiven/wordgrinder/blob/4aa462e050e0d191e89b298b55ceb7db40e3ae26/src/lua/settings.lua

should really use HOME/.config/wordgrinder.settings, at least on *Nix systems to avoid cluttering up home and to follow the XDG specification found here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

This helps standardize things and makes ls -a of a home folder readable.

**Comment by davidgiven** [comment]
Honestly, I find that convention really annoying, and it makes things complicated (such as needing to create the .config directory), so I'd rather not.
