### ISSUE TITLE
Version number? (apt-get, Ubuntu 16)

### ISSUE THREAD

**Issue by JpTiger** [davidgiven/wordgrinder#75]
Hi there,  I'm running an install of ubuntu server 16.04 and tried installing wordgrinder via apt-get. Worked great, but a couple features I was expecting didn't seem to work. So I went to File, About WordGrinder and saw that I was on WordGrinder 0.6.0. 

So, figuring the repository was outdated, I removed the program (apt-get remove wordgrinder)  cloned this repo from github with git,  got the dependencies to compile, compiled, installed, and ran it. 

...same thing happened. I'm still apparently on v 0.6.0.

The unlikely but simplest explanation is that the version number in 0.7.2 is wrongly still 0.6.0. More likely I did something silly and managed to not actually remove the old version and not actually build the old one (though if that's the case, the repository is out of date). 

Either way, thanks for a great program!

**Comment by davidgiven** [comment]
I once called a telephone repairman round because my phone wasn't ringing. Turns out I had the ringer turned off.

Did you make sure you ran the version in your home directory rather than the one in the Ubuntu package which would have been installed to `/usr/bin/wordgrinder` and would come before `$HOME/bin/wordgrinder` in your path?

**Comment by JpTiger** [comment]
...wait you mean I have to plug the printer in before it'll print?

That'd likely do it. I'd thought I'd uninstalled the one in /usr/bin/ but I bet that didn't actually happen. I've had to refresh the system since then so can't check, but will go straight from the git repo this time. Any plans to update the repo that apt-get pulls from in *buntu linux?
