### ISSUE TITLE
Makefile `ninja` command should be `ninja-build`

### ISSUE THREAD

**Issue by ItchyBugReporter** [davidgiven/wordgrinder#77]
[wordgrinder-ninja-build.txt](https://github.com/davidgiven/wordgrinder/files/3438813/wordgrinder-ninja-build.txt)
When trying to build wordgrinder 0.7.2 on CentOS 7, I get the following near then end of the output for make:

make: ninja: Command not found

After applying the attached patch (which replaces ninja with ninja-build in the Makefile), wordgrinder builds just fine.

This could very well be a distro-specific thing -- I don't know enough about ninja-build or CentOS packaging to tell either way.

**Comment by davidgiven** [comment]
(belatedly) CentOS uses nonstandard naming for ninja.
