### ISSUE TITLE
Feature Request: Export document set

### ISSUE THREAD

**Issue by ItchyBugReporter** [davidgiven/wordgrinder#78]
I've been using WordGrinder to work on a few novels of my own, and to help me keep things organized and switch chapters easily to reference past events (it's annoyingly difficult to mentally keep things straight in a long novel...), I've been putting each chapter within it's own "document" within the "document set" representing the novel the chapter belongs to (it's annoyingly difficult to scroll up ten chapters to find a specific line then back down again, and WordGrinder's "document sets containing documents" thing makes that much easier for me). However, it occurs to me that whatever publisher I submit to likely won't be using WordGrinder and will probably require some other (probably proprietary) format; this leaves me with the rather cumbersome task of individually exporting each chapter one-by-one (since they are in separate documents), then manually opening them one-by-one to copy-and-paste them into one single document.

It would be helpful to export the entire document set instead of requiring that things get exported as individual documents. There are two ways this feature could work:

1. Export each document into separate files.
2. Export entire document set into a single file.

Both options could be useful in different situations.

**Comment by semioticrobotic** [comment]
I agree that an "export document set" feature would be nice, @ItchyBugReporter. However, since the likelihood of having one before you've wrapped up your novel is low, I would encourage you not to overlook the mighty [pandoc](https://pandoc.org/) as a tool for easily and simply combining multiple files into a single document!

**Comment by davidgiven** [comment]
That's a reasonable feature request. If you can't wait, however, I've just written a little user script which does this: https://github.com/davidgiven/wordgrinder/blob/master/scripts/exportall.lua

To use, save it somewhere, and then from the command line, do:

```
$ wordgrinder --lua exportall.lua "yournovel.wg output.html"
```

(Note the non-standard quoting!) This will create multiple files called `output.1.something.html`, `output.2.somethingelse.html` etc for each subdoc in the document set. You should then be able to use pandoc to paste them together.
