### ISSUE TITLE
Inconsistent experience on FreeBSD

### ISSUE THREAD

**Issue by GregTheHun** [davidgiven/wordgrinder#79]
I would really like to be able to use this more, but the display tends to not show the top and bottom documents markers even when being set on the latest FreeBSD 12.0.

Granted, it is using version 0.6, but I would think that would affect that functionality.

**Comment by davidgiven** [comment]
Do you have any more information? e.g. are you on the console or using a terminal emulator? If the latter, which emulator and which font? Do the boxes around menus work? What do you see if you look at the Unicode sampler in the README?

**Comment by GregTheHun** [comment]
Sure thing, actually I’m just using it in the console. No boxes around menus either. No desktop in my case since I’m wanting to kind of pull a George R. R. Martin.

I will have to look at the Unicode sampler.

**Comment by davidgiven** [comment]
Chances are what's happening is simply that the FreeBSD console doesn't support Unicode. I've seen that there's work on a new console with does (vt?) but the old sc console doesn't. Unfortunately that's not anything WordGrinder has control over.

Your best option is probably to try installing jfbterm, which uses a graphics framebuffer to emulate a Unicode console.

**Comment by GregTheHun** [comment]
Where would the sampler be on FreeBSD?

**Comment by davidgiven** [comment]
It's one of the subdocuments in the main README.

**Comment by GregTheHun** [comment]
Yeah, with version 0.6 on FreeBSD, I'm not able to open it.

https://www.freebsd.org/cgi/ports.cgi?query=wordgrinder&stype=all

**Comment by davidgiven** [comment]
It should always open --- can you be more specific about the symptoms?

**Comment by GregTheHun** [comment]
So, at least here's a screenshot of the issue that I'm experiencing (running 0.6 which is what freebsd sees in repos):

![Annotation 2019-08-19 091050](https://user-images.githubusercontent.com/19254816/63272278-65f9d980-c261-11e9-82b0-4ba5c28392f8.png)

But if you need further data as well, I can look around and see what I can discover

**Comment by davidgiven** [comment]
The file format changed between 0.6 and 0.7, and you're loading the README from git (which is 0.7) with FreeBSD's 0.6. Load the README from the installed version instead.

Incidentally, do you know who I should kick to get FreeBSD to upgrade? 0.6 is really old (and buggy).

**Comment by GregTheHun** [comment]
Currently, it looks like from here: https://www.freebsd.org/cgi/ports.cgi?query=wordgrinder&stype=all

The maintainer of the package can be contacted at: vmagerya@gmail.com

**Comment by davidgiven** [comment]
(belatedly)

Email sent. Ta.

**Comment by davidgiven** [comment]
I believe this is obsolete.

**Comment by GregTheHun** [comment]
Just as an update, still using the older version, I guess possibly waiting for the next release:

https://www.freebsd.org/cgi/ports.cgi?query=wordgrinder&stype=all&sektion=all

**Comment by davidgiven** [comment]
I did email the maintainer, but never heard back --- I'm afraid it'll probably require a new one before anything happens.
