### ISSUE TITLE
Attempting to paste with an empty clipboard causes WordGrinder to crash

### ISSUE THREAD

**Issue by SpicyCarrot1550** [davidgiven/wordgrinder#82]
System Information:
Linux Mint 19.2 (Linux \<hostname\> 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

WordGrinder version: 0.7.1

Steps to reproduce:
1. Open document
2. (Optionally, type something)
3. ^V

Error message:

    Lua error: [string "src/lua/_prologue.lua"]:54: read from undefined local 'cl'
    stack traceback:
    	[C]: in function 'error'
    	[string "src/lua/_prologue.lua"]:54: in metamethod '__index'
    	[string "src/lua/redraw.lua"]:161: in function 'RedrawScreen'
    	[string "src/lua/forms.lua"]:492: in field 'Run'
    	[string "src/lua/ui.lua"]:99: in function 'ModalMessage'
    	[string "src/lua/main.lua"]:197: in function 'WordProcessor'
    	[string "src/lua/main.lua"]:365: in function 'Main'

**Comment by davidgiven** [comment]
That one's been fixed --- look for version 0.7.2. I can't tell whether Linux Mint has it or not (the package search engine seems to be broken).

**Comment by SpicyCarrot1550** [comment]
Yep, it seems like it’s just not in the repo yet:) I should have checked that first, sorry.

    home@<hostname>:~$ sudo apt-get update
    ...
    home@<hostname>:~$ apt-cache search wordgrinder
    wordgrinder - simple word processor for writing first drafts
    wordgrinder-doc - simple word processor for writing first drafts (documentation)
    wordgrinder-ncurses - simple word processor for writing first drafts (terminal version)
    wordgrinder-x11 - simple word processor for writing first drafts (X11 version)
    home@<hostname>:~$ apt-cache policy wordgrinder
    wordgrinder:
      Installed: 0.7.1-1
      Candidate: 0.7.1-1
      Version table:
     *** 0.7.1-1 500
            500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
            500 http://archive.ubuntu.com/ubuntu bionic/universe i386 Packages
            100 /var/lib/dpkg/status
    home@<hostname>:~$
