### ISSUE TITLE
Feature Request: Installation via homebrew for OSX

### ISSUE THREAD

**Issue by tekemperor** [davidgiven/wordgrinder#83]
I would like to be able to install this on a mac with

`brew cask install wordgrinder`
or 
`brew install wordgrinder`

**Comment by davidgiven** [comment]
Sorry, I can't help here --- I don't have any Mac devices and so can't do anything about Homebrew. Your best option is to persuade someone from the Homebrew community to package Wordgrinder (which would be great to see).
