### ISSUE TITLE
Request: update debian/ubuntu repo to current version (using apt-get gets you version 0.6)

### ISSUE THREAD

**Issue by JpTiger** [davidgiven/wordgrinder#84]
Hey there, this may be more trouble than it's worth, but this is a great program that I think a lot of Ubuntu derivative users like, and it would be great if they could install without having to compile by hand. Currently if you install from repos available in ubuntu-based linux distros, you get version 0.60. Any chance this could be updated to 0.7.2?

**Comment by davidgiven** [comment]
Ubuntu disco and above have WordGrinder 0.7.2. If you're getting 0.6.0, you must be using xenial, right?

Unfortunately I have no influence over which versions of the packages Ubuntu use. I'd like them to backport 0.7.2 to xenial as 0.6 has bugs in it, but sadly I'm not able to do that.
