### ISSUE TITLE
Dumb user problem: only xwordgrinder installed after compiling, wordgrinder (that woudl work in CLI environment) not installed

### ISSUE THREAD

**Issue by JpTiger** [davidgiven/wordgrinder#85]
I'm pretty sure this is because I'm doing something dumb, not a fault in the program, but here's what I've been doing after installing dependencies:

```
git clone http://www.github.com/davidgiven/wordgrinder/
cd wordgrinder
sudo make clean
sudo make all PREFIX=/usr/bin
sudo make install PREFIX=/usr/bin
```
After this, launching xwordgrinder works great, but when I try to run just "wordgrinder" from a CLI environment (X server not running), it says wordgrinder is not installed and to try installing it from apt-get. Xwordgrinder of course doesn't work without an X server.

For reference I'm on an old old eeePC 701 running Peppermint 7 Linux. What's the (probably very basic) mistake I'm making?

**Comment by davidgiven** [comment]
(on phone so brief)

If you do make clean and rebuild, the top of the log will tell you what packages it's found. I'd hazard a guess that it might not have libncursesw-dev installed.

**Comment by JpTiger** [comment]
Thanks for the response. I tried installing libncursesw5-dev, but it's already installed. The only things listed as not found when building are windows and specific lua packages (and it just uses the ones that are present anyway). Any ideas?

For the record, I've been working along with an older version I could install from xenial repos but recently found a file I made with current version of wordgrinder which of course won't open with the old version. That's why I'm only just responding to this now.

**Comment by davidgiven** [comment]
Can you do a `make clean` and `make` and post the logs?

**Comment by JpTiger** [comment]
Do you mean console output or is there a logfile generated somewhere?

Importantly some tinkering seems to have rendered this all moot. I tried installing without the added prefix language and it seems to have installed fine. It looks like it's installed in my home folder, but the command "wordgrinder" in CLI now works.

**Comment by davidgiven** [comment]
The console output, please.

The libraries are only detected when you do a clean build --- so if you installed the package and then just reran make it wouldn't autodetect them. But from your description that doesn't seem to be what's happening.

**Comment by JpTiger** [comment]
Console output is as follows:
```
sudo make clean
CLEAN
sudo make all PREFIX=/usr/bin
Bootstrapping build
Windows toolchain: not found
Detecting Curses in package 'ncursesw': found
Detecting FreeType2 in package 'freetype2': found
Detecting Xft in package '--cflags={-I/usr/include/X11} --libs={-lX11 -lXft}': found
Detecting Minizip in package 'builtin': found
Detecting LuaFileSystem in package 'builtin': found
Detecting uthash in package 'builtin': found
Detecting LuaBitOp in package 'builtin': found
Detecting Lua in package 'builtin': found
Detecting Lua in package 'lua-5.1': not found
Detecting Lua in package 'lua-5.2': found
Detecting Lua in package 'lua-5.3': not found
Detecting Lua in package 'luajit': not found
The preferred Lua package is: 'builtin'
[183/183] bin/wordgrinder-builtin-curs...bug/tests/windows-installdir.lua.stamp
~/github/wordgrinder $ sudo make install PREFIX=/usr/bin
[sudo] password for jptiger: 
[4/4] install -m 755 bin/xwordgrinder-...ase-stripped /usr/bin/bin/xwordgrinder
 ~/github/wordgrinder $ wordgrinder
The program 'wordgrinder' is currently not installed. You can install it by typing:
sudo apt install wordgrinder-ncurses
```

**Comment by davidgiven** [comment]
Aha.

Try `PREFIX=/usr`.

With `/usr/bin` it'll install the program into /usr/bin/bin/wordgrinder!

**Comment by JpTiger** [comment]
Got it! Since it's now working on my machine without issue, I'll leave that to the next person who runs into this (if anyone does). Thanks again for the quick response!
