### ISSUE TITLE
bindings not persistent?

### ISSUE THREAD

**Issue by Munchotaur** [davidgiven/wordgrinder#9]
If I rebind (for example) 'toggle status bar' to Ctrl-T, the binding doesn't persist on the next launch of Wordgrinder.

**Comment by davidgiven** [comment]
No, it doesn't. Bindings are saved as part of the document, so each document has its own set of bindings. There is a way to do global bindings, but it's a bit clunky --- look up wordgrinder.rc.lua in README.wg.
