### ISSUE TITLE
Fix for Terminal Inconsistencies

### ISSUE THREAD

**Issue by aric49** [davidgiven/wordgrinder#90]
Hi All, 

Not sure if this is the best place to share this finding or not. Please close the issue if there is a better place to post.   I started using WordGrinder a few weeks back and I really like this software a lot. Great work writing it! I really look forward to seeing what new features will be added in future releases. 

One irritating issue I have been working around in WordGrinder is inconsistencies in how the "UI" is displayed across different terminals and various platforms.  In standard Gnome-Terminal 3.34.2 in Fedora 31, everything works perfectly. However, in LXQT QTerminal, options  `CTL+`  commands don't work and neither does `SHIFT+Arrow Keys` to highlight text.  I have also seen in TMUX on various platforms that when `XTERM=xterm-256colors` is set, lines from the top of documents disappear and formatting gets really strange when you scroll through a document as seen in this previous issue: #43 

A work around I found if you launch wordgrinder using `XTERM=tmux`, it will work consistently across various types of terminals. Formatting, scrolling, highlighting, and CTRL commands all seem to work very well. It even appears that when you don't have TMUX installed, it still seems to work. 

If you're having issues with wordgrinder doing weird things in different terminals, I'd be interested to see what your findings are if you launch wordgrinder like so (even if you don't have TMUX installed):

```
$ XTERM=tmux wordgrinder my-doc.wg 
```

If you're a TMUX user like myself, you can set in your .tmux.conf:

```
set -g default-terminal "tmux"
```

Again, not sure if this is the best place to post this. It may help others who are experiencing weirdness between various terminals. 

**Update:** I also noticed that in QTerminal under LXQT, if you simply set:  `tmux`, you lose the 256 color support.   If that's the case, try using:  `tmux-256color`

**Comment by davidgiven** [comment]
Hello --- sorry for the delay, I've got a bit of a backlog... yes, there is a problem with terminal inconsistencies, but it's not anything WordGrinder can do about. Each terminal implements a slightly different set of functionality. Some terminals don't report shifted arrow keys, for example. There's also plenty of bugs in things like Unicode support.

The only real thing I can suggest is to use xwordgrinder if you really need all these key combinations to work, as it's the only reliable way to avoid the terminal issues. FWIW I use rxvt and haven't observed any problems there.

**Comment by aric49** [comment]
Thanks for the update @davidgiven  ---  I didn't realize there was x-based version of wordgrinder that could be run outside of the terminal.   Would you be able to provide details on how to install or build it?

**Comment by davidgiven** [comment]
I don't do the packaging for Fedora, so I don't really know how packages work there; but I think there's a single package containing all the different versions, so just try `xwordgrinder` and see what happens. If you want to build it yourself then provided the X11 development packages are installed it should Just Work --- look at the build log and it should tell you if they're detected.

**Comment by davidgiven** [comment]
I believe this is dealt with.
