### ISSUE TITLE
[Termux] Missing .wordgrinder.lua and rebinding keyboard shortcuts

### ISSUE THREAD

**Issue by aknight2015** [davidgiven/wordgrinder#91]
I use a bluetooth keyboard when I use Wordgrinder. When I hit the 'esc' key on the keyboard it my tablets "back" key. So instead of bringing down the menu for WordGrinder I go back to the Home Screen. I've tried to find .wordgrinder.lua to try and change the keybinding for the menu. It doesn't seem to exist. I could use some help on this issue, thanks. 

Update: Now when I try to run it I get
u0_a637@localhost ~> wordgrinder
Lua error: [string "src/lua/addons/debug.lua"]:18: bad argument #2 to 'string_format' (number has no integer representation)
stack traceback:
        [C]: in function 'string.format'
        [string "src/lua/addons/debug.lua"]:18: in local 'callback'
        [string "src/lua/events.lua"]:75: in function 'FireEvent'
        [string "src/lua/redraw.lua"]:81: in upvalue 'redrawstatus'
        [string "src/lua/redraw.lua"]:283: in function 'RedrawScreen'
        [string "src/lua/main.lua"]:112: in function 'WordProcessor'
        [string "src/lua/main.lua"]:367: in function 'Main'

I haven't modified any config file as I can't find any. Tried to uninstall, and reinstall. Same issue.

**Comment by davidgiven** [comment]
Sorry for the delay --- missed the email notification...

Escape's not bindable in WordGrinder; you'll need to configure termux to produce escape when you press the back key:

https://wiki.termux.com/wiki/Terminal_Settings

Regarding the crash: that looks like you turned on one of the global debugging options (File->Global Settings->Debugging options). These settings are stored in `~/.wordgrinder.settings`, so try editing or deleting that. But it shouldn't crash at all. What version of WordGrinder are you using, and where did you get it?

**Comment by davidgiven** [comment]
Closing as obsolete.
