### ISSUE TITLE
Windows installer: does not work on Windows 10 v.1809

### ISSUE THREAD

**Issue by tidux** [davidgiven/wordgrinder#92]
Asking the installer to run in Windows 8 compatibility mode succeeds, and Wordgrinder then runs as expected.

**Comment by davidgiven** [comment]
Do you have any details on how it fails? Win10 is my standard development machine, and it works there.

**Comment by tidux** [comment]
It just fails to execute.  Double clicking and msiexec both fail to run.  I don't have a debug environment available for Windows so I can't go into more detail than that.
