### ISSUE TITLE
Feature request: numbered lists style

### ISSUE THREAD

**Issue by garatma** [davidgiven/wordgrinder#94]
I use numbered lists a lot (more than bullet lists) but in wordgrinder I have to add them manually and the exported _.odt_ or _.html_ displays the numbers as plain text, which is not convenient.
Would it be possible to add a style very similar to the bullet **L** style but with numbers instead of bullets?
Thanks!

**Comment by davidgiven** [comment]
This should be plausible, although only with one level of lists (no nested lists). Let me have a look.

**Comment by davidgiven** [comment]
Done. And this ended up going down a rabbit hole of finding bugs in the importer and exporter to fix, which I have, so thank-you for that!

**Comment by garatma** [comment]
That souns great! Thank you!
