### ISSUE TITLE
Install on Debian 32 does not takes into account PREFIX

### ISSUE THREAD

**Issue by dg64** [davidgiven/wordgrinder#95]
running sudo make install PREFIX=/usr does not work as expected; the binaries are installed in the $HOME/bin directory and the man pages are not installed

**Comment by davidgiven** [comment]
You probably built without setting PREFIX --- the value gets baked into the ninja file. This isn't really optimal but I haven't found a good workaround yet.

```
make clean
make PREFIX=/usr
make install PREFIX=/usr
```

**Comment by dg64** [comment]
using make PREFIX=/usr and make install PREFIX=/usr works. I think you should update the README, because the clause PREFIX  is mentioned only in the make install step. Thank You for your quick answer.
