### ISSUE TITLE
Feature request: Special Characters

### ISSUE THREAD

**Issue by juanchocas** [davidgiven/wordgrinder#97]
I often use special characters that I can't type from my laptops keyboard, such as the long dash and the Spanish quotation charcters (not the regular English quotes). In thext editors, such as VIM, they can be accessed by going to the insert mode and then hitting CTRL+k, which allows you to type a combination of characters that is then transformed into the special character you're looking for. The way I've currently solved this is by having a separate document with the special characters I uset the most and copying them from there whenver I need to, but it would be awesome to have a "CTRL+k" equivalent straight from Wordgrinder.

**Comment by davidgiven** [comment]
You should be able to type them directly using whatever input mechanism your platform has --- e.g. on Linux I can press COMPOSE DASH DASH DASH to get a long dash. Which platform are you using?

**Comment by juanchocas** [comment]
Sorry to have raised this request without knowing about the COMPOSE key. I did look around for ways to insert special characters, but somehow I didn't get to this feature. I'm sort of a nube, so I'm still discovering a lot of stuff on my new Debian install. Thanks for letting me know about this and also for the amazing piece of software that Wordgrinder is.

**Comment by davidgiven** [comment]
Belatedly --- thanks very much! I'm glad it's working for you.
